const rt = {
  general: {
    widgetVisible: false,
    promoWidgetVisible: false,
    sign: "ghh",
  },
  session: {
    signature:
      "I5HMcUA2wX4=|Dpe7JrH2FXsOrz2+PUiHnhm+QOlOeVqfbVyteChVv9A8NqdTOIneTNUvPvbiJNSomkAOWOZrxJI57lHjoTsV+7XZ/7BEAIpcnG3hjlKMxvwUlppPot97bwz6PfXNPjItdVO1ExMY+yk=",
    sessionLoading: false,
    lowFareAvailabilityLoading: false,
    lowFareAvailabilityResponse: null,
    flightAvailabilityLoading: false,
    flightParams: {
      departureStation: "ABV",
      arrivalStation: "LOS",
      beginDate: "2022-08-28",
      endDate: "2022-08-28",
      returnDate: null,
      promoCode: "",
      ADT: 1,
      CHD: 0,
      INF: 0,
      isRoundTrip: null,
      signature:
        "I5HMcUA2wX4=|Dpe7JrH2FXsOrz2+PUiHnhm+QOlOeVqfbVyteChVv9A8NqdTOIneTNUvPvbiJNSomkAOWOZrxJI57lHjoTsV+7XZ/7BEAIpcnG3hjlKMxvwUlppPot97bwz6PfXNPjItdVO1ExMY+yk=",
    },
    availabilityResponse: {
      Error: null,
      GetTripAvailabilityResponse: {
        Schedules: [
          [
            {
              DepartureDate: "2022-08-28T00:00:00",
              DepartureDateSpecified: true,
              DepartureStation: "ABV",
              ArrivalStation: "LOS",
              Journeys: [
                {
                  NotForGeneralUse: false,
                  NotForGeneralUseSpecified: true,
                  Segments: [
                    {
                      ActionStatusCode: "",
                      ArrivalStation: "LOS",
                      CabinOfService: " ",
                      ChangeReasonCode: "",
                      DepartureStation: "ABV",
                      PriorityCode: "",
                      SegmentType: "",
                      STA: "2022-08-28T09:55:00",
                      STASpecified: true,
                      STD: "2022-08-28T08:20:00",
                      STDSpecified: true,
                      International: false,
                      InternationalSpecified: true,
                      FlightDesignator: {
                        CarrierCode: "Q9",
                        FlightNumber: " 301",
                        OpSuffix: " ",
                      },
                      XrefFlightDesignator: {
                        CarrierCode: "",
                        FlightNumber: "",
                        OpSuffix: "",
                      },
                      Fares: [
                        {
                          AvailableCount: 66,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "R",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "FLEX",
                          FareBasisCode: "RFOW",
                          FareSequence: 1,
                          FareSequenceSpecified: true,
                          FareClassOfService: "R",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "R",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 300,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 300,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 5165,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 5165,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "RFOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GF",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~R~~Q9~RFOW~FLEX~~2~1~NABVLOS0020010~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 2,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          AvailableCount: 6,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "S",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "SAVR",
                          FareBasisCode: "SSOW",
                          FareSequence: 2,
                          FareSequenceSpecified: true,
                          FareClassOfService: "S",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "S",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 27000,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 27000,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 6500,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 6500,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "SSOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GS",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~S~~Q9~SSOW~SAVR~~4~2~NABVLOS0040020~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 4,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          AvailableCount: 6,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "S",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "CLSC",
                          FareBasisCode: "SCOW",
                          FareSequence: 2,
                          FareSequenceSpecified: true,
                          FareClassOfService: "S",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "S",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 33667,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 33667,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 6833,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 6833,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "SCOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GC",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~S~~Q9~SCOW~CLSC~~4~2~NABVLOS0040020~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 4,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      Legs: [
                        {
                          ArrivalStation: "LOS",
                          DepartureStation: "ABV",
                          STA: "2022-08-28T09:55:00",
                          STASpecified: true,
                          STD: "2022-08-28T08:20:00",
                          STDSpecified: true,
                          FlightDesignator: {
                            CarrierCode: "Q9",
                            FlightNumber: " 301",
                            OpSuffix: " ",
                          },
                          LegInfo: {
                            AdjustedCapacity: 70,
                            AdjustedCapacitySpecified: true,
                            EquipmentType: "AT7",
                            EquipmentTypeSuffix: "",
                            ArrivalTerminal: "",
                            ArrvLTV: 60,
                            ArrvLTVSpecified: true,
                            Capacity: 70,
                            CapacitySpecified: true,
                            CodeShareIndicator: " ",
                            DepartureTerminal: "",
                            DeptLTV: 60,
                            DeptLTVSpecified: true,
                            ETicket: true,
                            ETicketSpecified: true,
                            FlifoUpdated: false,
                            FlifoUpdatedSpecified: true,
                            IROP: false,
                            IROPSpecified: true,
                            Status: 0,
                            StatusSpecified: true,
                            Lid: 70,
                            LidSpecified: true,
                            OnTime: " ",
                            PaxSTA: "2022-08-28T09:55:00",
                            PaxSTASpecified: true,
                            PaxSTD: "2022-08-28T08:20:00",
                            PaxSTDSpecified: true,
                            PRBCCode: "Y68",
                            ScheduleServiceType: "J",
                            Sold: 4,
                            SoldSpecified: true,
                            OutMoveDays: 0,
                            OutMoveDaysSpecified: true,
                            BackMoveDays: 0,
                            BackMoveDaysSpecified: true,
                            LegNests: [],
                            LegSSRs: [],
                            OperatingFlightNumber: "    ",
                            OperatedByText: "",
                            OperatingCarrier: "",
                            OperatingOpSuffix: " ",
                            SubjectToGovtApproval: false,
                            SubjectToGovtApprovalSpecified: true,
                            MarketingCode: "",
                            ChangeOfDirection: false,
                            ChangeOfDirectionSpecified: true,
                            MarketingOverride: false,
                            MarketingOverrideSpecified: true,
                            AircraftOwner: "",
                            State: 1,
                            StateSpecified: true,
                          },
                          OperationsInfo: null,
                          InventoryLegID: 14756,
                          InventoryLegIDSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      PaxBags: [],
                      PaxSeats: [],
                      PaxSSRs: [],
                      PaxSegments: [],
                      PaxTickets: [],
                      PaxSeatPreferences: [],
                      SalesDate: "9999-12-31T00:00:00Z",
                      SalesDateSpecified: true,
                      SegmentSellKey:
                        "Q9~ 301~ ~~ABV~08/28/2022 08:20~LOS~08/28/2022 09:55~~",
                      PaxScores: [],
                      ChannelType: 0,
                      ChannelTypeSpecified: true,
                      AvailabilitySourceCode: "",
                      InventorySourceCode: "",
                      State: 1,
                      StateSpecified: true,
                    },
                  ],
                  JourneySellKey:
                    "Q9~ 301~ ~~ABV~08/28/2022 08:20~LOS~08/28/2022 09:55~~",
                  PackageIndicator: "",
                  State: 0,
                  StateSpecified: true,
                },
                {
                  NotForGeneralUse: false,
                  NotForGeneralUseSpecified: true,
                  Segments: [
                    {
                      ActionStatusCode: "",
                      ArrivalStation: "LOS",
                      CabinOfService: " ",
                      ChangeReasonCode: "",
                      DepartureStation: "ABV",
                      PriorityCode: "",
                      SegmentType: "",
                      STA: "2022-08-28T19:30:00",
                      STASpecified: true,
                      STD: "2022-08-28T17:55:00",
                      STDSpecified: true,
                      International: false,
                      InternationalSpecified: true,
                      FlightDesignator: {
                        CarrierCode: "Q9",
                        FlightNumber: " 309",
                        OpSuffix: " ",
                      },
                      XrefFlightDesignator: {
                        CarrierCode: "",
                        FlightNumber: "",
                        OpSuffix: "",
                      },
                      Fares: [
                        {
                          AvailableCount: 69,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "R",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "FLEX",
                          FareBasisCode: "RFOW",
                          FareSequence: 1,
                          FareSequenceSpecified: true,
                          FareClassOfService: "R",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "R",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 300,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 300,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 5165,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 5165,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "RFOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GF",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~R~~Q9~RFOW~FLEX~~2~1~NABVLOS0020010~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 2,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          AvailableCount: 9,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "S",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "SAVR",
                          FareBasisCode: "SSOW",
                          FareSequence: 2,
                          FareSequenceSpecified: true,
                          FareClassOfService: "S",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "S",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 27000,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 27000,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 6500,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 6500,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "SSOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GS",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~S~~Q9~SSOW~SAVR~~4~2~NABVLOS0040020~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 4,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          AvailableCount: 9,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "S",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "CLSC",
                          FareBasisCode: "SCOW",
                          FareSequence: 2,
                          FareSequenceSpecified: true,
                          FareClassOfService: "S",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "S",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 33667,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 33667,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 6833,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 6833,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "SCOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GC",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~S~~Q9~SCOW~CLSC~~4~2~NABVLOS0040020~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 4,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      Legs: [
                        {
                          ArrivalStation: "LOS",
                          DepartureStation: "ABV",
                          STA: "2022-08-28T19:30:00",
                          STASpecified: true,
                          STD: "2022-08-28T17:55:00",
                          STDSpecified: true,
                          FlightDesignator: {
                            CarrierCode: "Q9",
                            FlightNumber: " 309",
                            OpSuffix: " ",
                          },
                          LegInfo: {
                            AdjustedCapacity: 70,
                            AdjustedCapacitySpecified: true,
                            EquipmentType: "AT7",
                            EquipmentTypeSuffix: "",
                            ArrivalTerminal: "",
                            ArrvLTV: 60,
                            ArrvLTVSpecified: true,
                            Capacity: 70,
                            CapacitySpecified: true,
                            CodeShareIndicator: " ",
                            DepartureTerminal: "",
                            DeptLTV: 60,
                            DeptLTVSpecified: true,
                            ETicket: true,
                            ETicketSpecified: true,
                            FlifoUpdated: false,
                            FlifoUpdatedSpecified: true,
                            IROP: false,
                            IROPSpecified: true,
                            Status: 0,
                            StatusSpecified: true,
                            Lid: 70,
                            LidSpecified: true,
                            OnTime: " ",
                            PaxSTA: "2022-08-28T19:30:00",
                            PaxSTASpecified: true,
                            PaxSTD: "2022-08-28T17:55:00",
                            PaxSTDSpecified: true,
                            PRBCCode: "Y68",
                            ScheduleServiceType: "J",
                            Sold: 1,
                            SoldSpecified: true,
                            OutMoveDays: 0,
                            OutMoveDaysSpecified: true,
                            BackMoveDays: 0,
                            BackMoveDaysSpecified: true,
                            LegNests: [],
                            LegSSRs: [],
                            OperatingFlightNumber: "    ",
                            OperatedByText: "",
                            OperatingCarrier: "",
                            OperatingOpSuffix: " ",
                            SubjectToGovtApproval: false,
                            SubjectToGovtApprovalSpecified: true,
                            MarketingCode: "",
                            ChangeOfDirection: false,
                            ChangeOfDirectionSpecified: true,
                            MarketingOverride: false,
                            MarketingOverrideSpecified: true,
                            AircraftOwner: "",
                            State: 1,
                            StateSpecified: true,
                          },
                          OperationsInfo: null,
                          InventoryLegID: 16952,
                          InventoryLegIDSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      PaxBags: [],
                      PaxSeats: [],
                      PaxSSRs: [],
                      PaxSegments: [],
                      PaxTickets: [],
                      PaxSeatPreferences: [],
                      SalesDate: "9999-12-31T00:00:00Z",
                      SalesDateSpecified: true,
                      SegmentSellKey:
                        "Q9~ 309~ ~~ABV~08/28/2022 17:55~LOS~08/28/2022 19:30~~",
                      PaxScores: [],
                      ChannelType: 0,
                      ChannelTypeSpecified: true,
                      AvailabilitySourceCode: "",
                      InventorySourceCode: "",
                      State: 1,
                      StateSpecified: true,
                    },
                  ],
                  JourneySellKey:
                    "Q9~ 309~ ~~ABV~08/28/2022 17:55~LOS~08/28/2022 19:30~~",
                  PackageIndicator: "",
                  State: 0,
                  StateSpecified: true,
                },
                {
                  NotForGeneralUse: false,
                  NotForGeneralUseSpecified: true,
                  Segments: [
                    {
                      ActionStatusCode: "",
                      ArrivalStation: "LOS",
                      CabinOfService: " ",
                      ChangeReasonCode: "",
                      DepartureStation: "ABV",
                      PriorityCode: "",
                      SegmentType: "",
                      STA: "2022-08-28T22:55:00",
                      STASpecified: true,
                      STD: "2022-08-28T21:20:00",
                      STDSpecified: true,
                      International: false,
                      InternationalSpecified: true,
                      FlightDesignator: {
                        CarrierCode: "Q9",
                        FlightNumber: " 303",
                        OpSuffix: " ",
                      },
                      XrefFlightDesignator: {
                        CarrierCode: "",
                        FlightNumber: "",
                        OpSuffix: "",
                      },
                      Fares: [
                        {
                          AvailableCount: 70,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "R",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "FLEX",
                          FareBasisCode: "RFOW",
                          FareSequence: 1,
                          FareSequenceSpecified: true,
                          FareClassOfService: "R",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "R",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 300,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 300,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 5165,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 5165,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "RFOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GF",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~R~~Q9~RFOW~FLEX~~2~1~NABVLOS0020010~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 2,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          AvailableCount: 10,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "S",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "SAVR",
                          FareBasisCode: "SSOW",
                          FareSequence: 2,
                          FareSequenceSpecified: true,
                          FareClassOfService: "S",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "S",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 27000,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 27000,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 6500,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 6500,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "SSOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GS",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~S~~Q9~SSOW~SAVR~~4~2~NABVLOS0040020~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 4,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          AvailableCount: 10,
                          AvailableCountSpecified: true,
                          Status: 0,
                          StatusSpecified: true,
                          SSRIndexes: null,
                          ServiceBundleSetCode: "",
                          ServiceBundleOfferIndexes: [],
                          ClassOfService: "S",
                          ClassType: "",
                          RuleTariff: "",
                          CarrierCode: "Q9",
                          RuleNumber: "CLSC",
                          FareBasisCode: "SCOW",
                          FareSequence: 2,
                          FareSequenceSpecified: true,
                          FareClassOfService: "S",
                          FareStatus: 0,
                          FareStatusSpecified: true,
                          FareApplicationType: 0,
                          FareApplicationTypeSpecified: true,
                          OriginalClassOfService: "S",
                          XrefClassOfService: "",
                          PaxFares: [
                            {
                              PaxType: "ADT",
                              PaxDiscountCode: "",
                              FareDiscountCode: "",
                              ServiceCharges: [
                                {
                                  ChargeType: 0,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 33667,
                                  AmountSpecified: true,
                                  ChargeDetail: "",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 33667,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                                {
                                  ChargeType: 5,
                                  ChargeTypeSpecified: true,
                                  CollectType: 0,
                                  CollectTypeSpecified: true,
                                  ChargeCode: "",
                                  TicketCode: "",
                                  CurrencyCode: "NGN",
                                  Amount: 6833,
                                  AmountSpecified: true,
                                  ChargeDetail: "TaxFeeSum",
                                  ForeignCurrencyCode: "NGN",
                                  ForeignAmount: 6833,
                                  ForeignAmountSpecified: true,
                                  State: 1,
                                  StateSpecified: true,
                                },
                              ],
                              TicketFareBasisCode: "SCOW",
                              ProofOfStatusRequired: false,
                              ProofOfStatusRequiredSpecified: true,
                              State: 1,
                              StateSpecified: true,
                            },
                          ],
                          ProductClass: "GC",
                          IsAllotmentMarketFare: false,
                          IsAllotmentMarketFareSpecified: true,
                          TravelClassCode: " ",
                          FareSellKey:
                            "0~S~~Q9~SCOW~CLSC~~4~2~NABVLOS0040020~X",
                          InboundOutbound: 0,
                          InboundOutboundSpecified: true,
                          FareLink: 4,
                          FareLinkSpecified: true,
                          FareDesignator: null,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      Legs: [
                        {
                          ArrivalStation: "LOS",
                          DepartureStation: "ABV",
                          STA: "2022-08-28T22:55:00",
                          STASpecified: true,
                          STD: "2022-08-28T21:20:00",
                          STDSpecified: true,
                          FlightDesignator: {
                            CarrierCode: "Q9",
                            FlightNumber: " 303",
                            OpSuffix: " ",
                          },
                          LegInfo: {
                            AdjustedCapacity: 70,
                            AdjustedCapacitySpecified: true,
                            EquipmentType: "AT7",
                            EquipmentTypeSuffix: "",
                            ArrivalTerminal: "",
                            ArrvLTV: 60,
                            ArrvLTVSpecified: true,
                            Capacity: 70,
                            CapacitySpecified: true,
                            CodeShareIndicator: " ",
                            DepartureTerminal: "",
                            DeptLTV: 60,
                            DeptLTVSpecified: true,
                            ETicket: true,
                            ETicketSpecified: true,
                            FlifoUpdated: false,
                            FlifoUpdatedSpecified: true,
                            IROP: false,
                            IROPSpecified: true,
                            Status: 0,
                            StatusSpecified: true,
                            Lid: 70,
                            LidSpecified: true,
                            OnTime: " ",
                            PaxSTA: "2022-08-28T22:55:00",
                            PaxSTASpecified: true,
                            PaxSTD: "2022-08-28T21:20:00",
                            PaxSTDSpecified: true,
                            PRBCCode: "Y68",
                            ScheduleServiceType: "J",
                            Sold: 0,
                            SoldSpecified: true,
                            OutMoveDays: 0,
                            OutMoveDaysSpecified: true,
                            BackMoveDays: 0,
                            BackMoveDaysSpecified: true,
                            LegNests: [],
                            LegSSRs: [],
                            OperatingFlightNumber: "    ",
                            OperatedByText: "",
                            OperatingCarrier: "",
                            OperatingOpSuffix: " ",
                            SubjectToGovtApproval: false,
                            SubjectToGovtApprovalSpecified: true,
                            MarketingCode: "",
                            ChangeOfDirection: false,
                            ChangeOfDirectionSpecified: true,
                            MarketingOverride: false,
                            MarketingOverrideSpecified: true,
                            AircraftOwner: "",
                            State: 1,
                            StateSpecified: true,
                          },
                          OperationsInfo: null,
                          InventoryLegID: 16762,
                          InventoryLegIDSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      PaxBags: [],
                      PaxSeats: [],
                      PaxSSRs: [],
                      PaxSegments: [],
                      PaxTickets: [],
                      PaxSeatPreferences: [],
                      SalesDate: "9999-12-31T00:00:00Z",
                      SalesDateSpecified: true,
                      SegmentSellKey:
                        "Q9~ 303~ ~~ABV~08/28/2022 21:20~LOS~08/28/2022 22:55~~",
                      PaxScores: [],
                      ChannelType: 0,
                      ChannelTypeSpecified: true,
                      AvailabilitySourceCode: "",
                      InventorySourceCode: "",
                      State: 1,
                      StateSpecified: true,
                    },
                  ],
                  JourneySellKey:
                    "Q9~ 303~ ~~ABV~08/28/2022 21:20~LOS~08/28/2022 22:55~~",
                  PackageIndicator: "",
                  State: 0,
                  StateSpecified: true,
                },
              ],
              IncludesTaxesAndFees: true,
              IncludesTaxesAndFeesSpecified: true,
            },
          ],
        ],
        ServiceBundleOfferList: [],
        OtherServiceInfoList: [],
      },
    },
    sellFlightLoading: false,
    sellResponse: {
      BookingUpdateResponseData: {
        Success: {
          RecordLocator: "",
          PNRAmount: {
            BalanceDue: 40500,
            BalanceDueSpecified: true,
            AuthorizedBalanceDue: 40500,
            AuthorizedBalanceDueSpecified: true,
            SegmentCount: 1,
            SegmentCountSpecified: true,
            PassiveSegmentCount: 0,
            PassiveSegmentCountSpecified: true,
            TotalCost: 40500,
            TotalCostSpecified: true,
            PointsBalanceDue: 0,
            PointsBalanceDueSpecified: true,
            TotalPointCost: 0,
            TotalPointCostSpecified: true,
            AlternateCurrencyCode: "",
            AlternateCurrencyBalanceDue: 0,
            AlternateCurrencyBalanceDueSpecified: true,
          },
        },
        Warning: null,
        Error: null,
        OtherServiceInformations: null,
      },
    },
    sellInfantLoading: false,
    sellInfantResponse: null,
    sessionPassengers: [
      {
        id: 0,
        firstName: "olabamipe",
        lastName: "tee",
        title: "Mrs",
        dob: "2022-07-26",
        type: "ADT",
        typeCount: 1,
      },
    ],
    sessionInfants: null,
    sessionContact: {
      title: "Mrs",
      firstName: "olabamipe",
      lastName: "tee",
      phone: "908976564532",
      email: "teeol248@gmail.com",
    },
    sessionSegmentDetails: {
      flightDesignator: {
        carrierCode: "Q9",
        flightNumber: " 309",
      },
      std: "2022-08-28T17:55:00",
      departureStation: "ABV",
      arrivalStation: "LOS",
    },
    updatePassengersLoading: false,
    passengersResponse: {
      BookingUpdateResponseData: {
        Success: {
          RecordLocator: "",
          PNRAmount: {
            BalanceDue: 40500,
            BalanceDueSpecified: true,
            AuthorizedBalanceDue: 40500,
            AuthorizedBalanceDueSpecified: true,
            SegmentCount: 1,
            SegmentCountSpecified: true,
            PassiveSegmentCount: 0,
            PassiveSegmentCountSpecified: true,
            TotalCost: 40500,
            TotalCostSpecified: true,
            PointsBalanceDue: 0,
            PointsBalanceDueSpecified: true,
            TotalPointCost: 0,
            TotalPointCostSpecified: true,
            AlternateCurrencyCode: "",
            AlternateCurrencyBalanceDue: 0,
            AlternateCurrencyBalanceDueSpecified: true,
          },
        },
        Warning: null,
        Error: null,
        OtherServiceInformations: null,
      },
    },
    updateContactsLoading: false,
    contactsResponse: {
      BookingUpdateResponseData: {
        Success: {
          RecordLocator: "",
          PNRAmount: {
            BalanceDue: 40500,
            BalanceDueSpecified: true,
            AuthorizedBalanceDue: 40500,
            AuthorizedBalanceDueSpecified: true,
            SegmentCount: 1,
            SegmentCountSpecified: true,
            PassiveSegmentCount: 0,
            PassiveSegmentCountSpecified: true,
            TotalCost: 40500,
            TotalCostSpecified: true,
            PointsBalanceDue: 0,
            PointsBalanceDueSpecified: true,
            TotalPointCost: 0,
            TotalPointCostSpecified: true,
            AlternateCurrencyCode: "",
            AlternateCurrencyBalanceDue: 0,
            AlternateCurrencyBalanceDueSpecified: true,
          },
        },
        Warning: null,
        Error: null,
        OtherServiceInformations: null,
      },
    },
    paymentBookingLoading: false,
    paymentBookingResponse: null,
    bookingCommitLoading: false,
    bookingCommitResponse: {
      BookingUpdateResponseData: {
        Success: {
          RecordLocator: "XYQ4HA",
          PNRAmount: {
            BalanceDue: 40500,
            BalanceDueSpecified: true,
            AuthorizedBalanceDue: 40500,
            AuthorizedBalanceDueSpecified: true,
            SegmentCount: 1,
            SegmentCountSpecified: true,
            PassiveSegmentCount: 0,
            PassiveSegmentCountSpecified: true,
            TotalCost: 40500,
            TotalCostSpecified: true,
            PointsBalanceDue: 0,
            PointsBalanceDueSpecified: true,
            TotalPointCost: 0,
            TotalPointCostSpecified: true,
            AlternateCurrencyCode: "",
            AlternateCurrencyBalanceDue: 0,
            AlternateCurrencyBalanceDueSpecified: true,
          },
        },
        Warning: null,
        Error: null,
        OtherServiceInformations: null,
      },
    },
    bookingResponseLoading: false,
    bookingResponse: null,
    SSRAvailabilityLoading: false,
    SSRAvailabilityResponse: {
      Error: null,
      SSRAvailabilityForBookingResponse: {
        SSRSegmentList: [
          {
            LegKey: {
              DepartureDate: "2022-08-28T00:00:00",
              DepartureDateSpecified: true,
              DepartureStation: "ABV",
              ArrivalStation: "LOS",
              CarrierCode: "Q9",
              FlightNumber: " 309",
              OpSuffix: " ",
            },
            AvailablePaxSSRList: [
              {
                SSRCode: "X20",
                InventoryControlled: true,
                InventoryControlledSpecified: true,
                NonInventoryControlled: false,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 100,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "XBAG20",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "XBAG20",
                          TicketCode: "X20",
                          CurrencyCode: "NGN",
                          Amount: 5000,
                          AmountSpecified: true,
                          ChargeDetail: "XBAG 20KG",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 5000,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                        {
                          ChargeType: 5,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "NG",
                          TicketCode: "NG ",
                          CurrencyCode: "NGN",
                          Amount: 250,
                          AmountSpecified: true,
                          ChargeDetail: "ABV-LOS",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 250,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
              {
                SSRCode: "X15",
                InventoryControlled: true,
                InventoryControlledSpecified: true,
                NonInventoryControlled: false,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 100,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "XBAG15",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "XBAG15",
                          TicketCode: "X15",
                          CurrencyCode: "NGN",
                          Amount: 4500,
                          AmountSpecified: true,
                          ChargeDetail: "XBAG 15KG",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 4500,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                        {
                          ChargeType: 5,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "NG",
                          TicketCode: "NG ",
                          CurrencyCode: "NGN",
                          Amount: 225,
                          AmountSpecified: true,
                          ChargeDetail: "ABV-LOS",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 225,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
              {
                SSRCode: "X10",
                InventoryControlled: true,
                InventoryControlledSpecified: true,
                NonInventoryControlled: false,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 100,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "XBAG10",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "XBAG10",
                          TicketCode: "X10",
                          CurrencyCode: "NGN",
                          Amount: 8000,
                          AmountSpecified: true,
                          ChargeDetail: "XBAG 10KG",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 8000,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                        {
                          ChargeType: 5,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "NG",
                          TicketCode: "NG ",
                          CurrencyCode: "NGN",
                          Amount: 400,
                          AmountSpecified: true,
                          ChargeDetail: "ABV-LOS",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 400,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
              {
                SSRCode: "PCK",
                InventoryControlled: false,
                InventoryControlledSpecified: true,
                NonInventoryControlled: true,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 0,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "PCK",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "PCK",
                          TicketCode: "PCK",
                          CurrencyCode: "NGN",
                          Amount: 3000,
                          AmountSpecified: true,
                          ChargeDetail: "Priority C",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 3000,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
              {
                SSRCode: "MAAS",
                InventoryControlled: true,
                InventoryControlledSpecified: true,
                NonInventoryControlled: false,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 5,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [],
                SSRLegList: [],
              },
              {
                SSRCode: "INFT",
                InventoryControlled: true,
                InventoryControlledSpecified: true,
                NonInventoryControlled: false,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 6,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "INFT",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "INFT",
                          TicketCode: "INF",
                          CurrencyCode: "NGN",
                          Amount: 10000,
                          AmountSpecified: true,
                          ChargeDetail: "Infant in ",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 10000,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
              {
                SSRCode: "I23",
                InventoryControlled: false,
                InventoryControlledSpecified: true,
                NonInventoryControlled: true,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 0,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "IBAG23",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "IBAG23",
                          TicketCode: "I23",
                          CurrencyCode: "NGN",
                          Amount: 0,
                          AmountSpecified: true,
                          ChargeDetail: "for free",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 0,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
              {
                SSRCode: "I15",
                InventoryControlled: false,
                InventoryControlledSpecified: true,
                NonInventoryControlled: true,
                NonInventoryControlledSpecified: true,
                SeatDependent: false,
                SeatDependentSpecified: true,
                NonSeatDependent: true,
                NonSeatDependentSpecified: true,
                Available: 0,
                AvailableSpecified: true,
                PassengerNumberList: [0],
                PaxSSRPriceList: [
                  {
                    PaxFee: {
                      ActionStatusCode: "NN",
                      FeeCode: "IBAG15",
                      FeeDetail: "",
                      FeeNumber: 0,
                      FeeNumberSpecified: true,
                      FeeType: 6,
                      FeeTypeSpecified: true,
                      FeeOverride: false,
                      FeeOverrideSpecified: true,
                      FlightReference: "",
                      Note: "",
                      SSRCode: "",
                      SSRNumber: 0,
                      SSRNumberSpecified: true,
                      PaymentNumber: 0,
                      PaymentNumberSpecified: true,
                      ServiceCharges: [
                        {
                          ChargeType: 6,
                          ChargeTypeSpecified: true,
                          CollectType: 0,
                          CollectTypeSpecified: true,
                          ChargeCode: "IBAG15",
                          TicketCode: "I15",
                          CurrencyCode: "NGN",
                          Amount: 4500,
                          AmountSpecified: true,
                          ChargeDetail: "Inclusive ",
                          ForeignCurrencyCode: "NGN",
                          ForeignAmount: 4500,
                          ForeignAmountSpecified: true,
                          State: 0,
                          StateSpecified: true,
                        },
                      ],
                      CreatedDate: "2022-08-25T00:40:40.9362238Z",
                      CreatedDateSpecified: true,
                      IsProtected: false,
                      IsProtectedSpecified: true,
                      FeeApplicationType: 3,
                      FeeApplicationTypeSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    PassengerNumberList: [0],
                  },
                ],
                SSRLegList: [],
              },
            ],
          },
        ],
        OtherServiceInfoList: [],
      },
    },
    sellSSRLoading: false,
    sellSSRResponse: null,
  },
  payment: {
    gatewaysLoading: false,
    gatewaysResponse: {
      success: true,
      code: 0,
      locale: "en",
      message: "OK",
      data: {
        items: [
          {
            id: 1,
            name: "Paystack",
            public_key: "pk_test_0941e052e394c4120c1e045f3b7a53ecbda3375b",
            secret_key: "sk_test_cfe7a0167d6a4a7421c461aa5ac05284c6d9706a",
            encryption_key: "3b7a53ecbda3375b",
            logo: "paymentmedia/paystack.png",
            callback_url: "https://gacms.klluster.com/callback",
            description:
              'By selecting "Pay" you confirm reservation of selected services and agree with the conditions of carriage and the fare application rules of Green Africa. You will be redirected to our secure payment checkout.',
            metadata: null,
            rank: 1,
            active: 1,
            created_at: "2022-08-17T04:33:45.000000Z",
            updated_at: "2022-08-21T18:41:57.000000Z",
            logo_url:
              "https://gacms.klluster.com/storage/paymentmedia/paystack.png",
          },
          {
            id: 2,
            name: "Flutterwave",
            public_key: "FLWPUBK_TEST-af7d84d9e229d1ced9ff3eabb7cb18a7-X",
            secret_key: "FLWSECK_TEST-6cf97704e4e6ba278139cd65043b47ae-X",
            encryption_key: null,
            logo: "paymentmedia/flutterwave.png",
            callback_url: "https://gacms.klluster.com/callback",
            description:
              'By selecting "Pay" you confirm reservation of selected services and agree with the conditions of carriage and the fare application rules of Green Africa. You will be redirected to our secure payment checkout.',
            metadata: null,
            rank: 2,
            active: 1,
            created_at: "2022-08-17T04:33:45.000000Z",
            updated_at: "2022-08-21T18:42:07.000000Z",
            logo_url:
              "https://gacms.klluster.com/storage/paymentmedia/flutterwave.png",
          },
        ],
      },
    },
    paymentLoading: false,
    paymentResponse: null,
    verifyPaymentLoading: false,
    verifyPaymentResponse: null,
  },
};
