const store = {
  general: {
    widgetVisible: false,
    promoWidgetVisible: false,
    sign: "ghh",
  },
  session: {
    isLoading: false,
    signature:
      "g3OnnPmiED8=|gwyVDP/9cRHkhLKGeU1+qjiqnjP3qQ88kgB+N9IG7JxZS+t1KC3nljqXNmrQe4i0Zp7Imi7KSJdYZeANJd9GS3XSG6AlQgzSErwq4wxjeZbhVqCYKTfmX4Hu2d1BhF5VPf9FpXDeMHU=",
    sessionLoading: false,
    lowFareAvailabilityLoading: false,
    lowFareAvailabilityResponse: null,
    flightAvailabilityLoading: false,
    flightParams: null,
    availabilityResponse: null,
    selectedSessionJourney: null,
    selectedSessionFare: null,
    sellFlightLoading: false,
    sellResponse: null,
    sellInfantLoading: false,
    sellInfantResponse: null,
    sessionPassengers: null,
    sessionInfants: null,
    sessionContact: null,
    sessionSSRs: null,
    updatePassengersLoading: false,
    passengersResponse: null,
    updateContactsLoading: false,
    contactsResponse: null,
    paymentBookingLoading: false,
    paymentBookingResponse: null,
    bookingCommitLoading: false,
    bookingCommitResponse: null,
    bookingResponseLoading: false,
    bookingResponse: {
      Error: null,
      Booking: {
        State: 1,
        StateSpecified: true,
        RecordLocator: "U3RZRV",
        CurrencyCode: "NGN",
        PaxCount: 1,
        PaxCountSpecified: true,
        SystemCode: "",
        BookingID: 38413,
        BookingIDSpecified: true,
        BookingParentID: 0,
        BookingParentIDSpecified: true,
        ParentRecordLocator: "",
        BookingChangeCode: "",
        GroupName: "",
        BookingInfo: {
          BookingStatus: 2,
          BookingStatusSpecified: true,
          BookingType: "",
          ChannelType: 4,
          ChannelTypeSpecified: true,
          CreatedDate: "2022-08-30T20:35:05.203Z",
          CreatedDateSpecified: true,
          ExpiredDate: "2022-09-01T07:20:00Z",
          ExpiredDateSpecified: true,
          ModifiedDate: "2022-08-30T20:36:13.037Z",
          ModifiedDateSpecified: true,
          PriceStatus: 2,
          PriceStatusSpecified: true,
          ProfileStatus: 1,
          ProfileStatusSpecified: true,
          ChangeAllowed: true,
          ChangeAllowedSpecified: true,
          CreatedAgentID: 409,
          CreatedAgentIDSpecified: true,
          ModifiedAgentID: 409,
          ModifiedAgentIDSpecified: true,
          BookingDate: "2022-08-30T20:35:05.203Z",
          BookingDateSpecified: true,
          OwningCarrierCode: "Q9",
          PaidStatus: 1,
          PaidStatusSpecified: true,
          ActivityDate: "2022-08-30T20:36:13.037",
          ActivityDateSpecified: true,
          State: 1,
          StateSpecified: true,
        },
        POS: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        SourcePOS: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        TypeOfSale: {
          PaxResidentCountry: "NG",
          PromotionCode: "",
          FareTypes: [],
          PromotionSold: false,
          PromotionSoldSpecified: true,
          State: 1,
          StateSpecified: true,
        },
        BookingHold: {
          HoldDateTime: "9999-12-31T00:00:00Z",
          HoldDateTimeSpecified: true,
          State: 1,
          StateSpecified: true,
        },
        BookingSum: {
          BalanceDue: 0,
          BalanceDueSpecified: true,
          AuthorizedBalanceDue: 0,
          AuthorizedBalanceDueSpecified: true,
          SegmentCount: 1,
          SegmentCountSpecified: true,
          PassiveSegmentCount: 0,
          PassiveSegmentCountSpecified: true,
          TotalCost: 64125,
          TotalCostSpecified: true,
          PointsBalanceDue: 0,
          PointsBalanceDueSpecified: true,
          TotalPointCost: 0,
          TotalPointCostSpecified: true,
          AlternateCurrencyCode: "",
          AlternateCurrencyBalanceDue: 0,
          AlternateCurrencyBalanceDueSpecified: true,
        },
        ReceivedBy: {
          ReceivedBy: "",
          ReceivedReference: "",
          ReferralCode: "",
          LatestReceivedBy: "",
          LatestReceivedReference: "",
          State: 1,
          StateSpecified: true,
        },
        RecordLocators: [],
        Passengers: [
          {
            PassengerPrograms: null,
            CustomerNumber: "",
            PassengerNumber: 0,
            PassengerNumberSpecified: true,
            FamilyNumber: 0,
            FamilyNumberSpecified: true,
            PaxDiscountCode: "",
            Names: [
              {
                FirstName: "olabamipe",
                MiddleName: "Olabamipe",
                LastName: "Olabamipe",
                Suffix: "",
                Title: "MRS",
                State: 1,
                StateSpecified: true,
              },
            ],
            Infant: null,
            PassengerInfo: {
              BalanceDue: 0,
              BalanceDueSpecified: true,
              Gender: 0,
              GenderSpecified: true,
              Nationality: "",
              ResidentCountry: "",
              TotalCost: 64125,
              TotalCostSpecified: true,
              WeightCategory: 1,
              WeightCategorySpecified: true,
              State: 1,
              StateSpecified: true,
            },
            PassengerProgram: {
              ProgramCode: "",
              ProgramLevelCode: "",
              ProgramNumber: "",
              State: 1,
              StateSpecified: true,
            },
            PassengerFees: [
              {
                ActionStatusCode: "HK",
                FeeCode: "XBAG20",
                FeeDetail: "",
                FeeNumber: 0,
                FeeNumberSpecified: true,
                FeeType: 6,
                FeeTypeSpecified: true,
                FeeOverride: false,
                FeeOverrideSpecified: true,
                FlightReference: "20220831 Q9 301 ABVLOS",
                Note: "",
                SSRCode: "X20",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                PaymentNumber: 0,
                PaymentNumberSpecified: true,
                ServiceCharges: [
                  {
                    ChargeType: 6,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "XBAG20",
                    TicketCode: "X20",
                    CurrencyCode: "NGN",
                    Amount: 5000,
                    AmountSpecified: true,
                    ChargeDetail: "XBAG 20KG",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 5000,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ChargeType: 5,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "NG",
                    TicketCode: "NG ",
                    CurrencyCode: "NGN",
                    Amount: 250,
                    AmountSpecified: true,
                    ChargeDetail: "ABV-LOS",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 250,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                CreatedDate: "2022-08-30T20:35:05.203Z",
                CreatedDateSpecified: true,
                IsProtected: false,
                IsProtectedSpecified: true,
                FeeApplicationType: 3,
                FeeApplicationTypeSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                FeeCode: "XBAG20",
                FeeDetail: "",
                FeeNumber: 1,
                FeeNumberSpecified: true,
                FeeType: 6,
                FeeTypeSpecified: true,
                FeeOverride: false,
                FeeOverrideSpecified: true,
                FlightReference: "20220831 Q9 301 ABVLOS",
                Note: "",
                SSRCode: "X20",
                SSRNumber: 2,
                SSRNumberSpecified: true,
                PaymentNumber: 0,
                PaymentNumberSpecified: true,
                ServiceCharges: [
                  {
                    ChargeType: 6,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "XBAG20",
                    TicketCode: "X20",
                    CurrencyCode: "NGN",
                    Amount: 5000,
                    AmountSpecified: true,
                    ChargeDetail: "XBAG 20KG",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 5000,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ChargeType: 5,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "NG",
                    TicketCode: "NG ",
                    CurrencyCode: "NGN",
                    Amount: 250,
                    AmountSpecified: true,
                    ChargeDetail: "ABV-LOS",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 250,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                CreatedDate: "2022-08-30T20:35:05.203Z",
                CreatedDateSpecified: true,
                IsProtected: false,
                IsProtectedSpecified: true,
                FeeApplicationType: 3,
                FeeApplicationTypeSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                FeeCode: "XBAG15",
                FeeDetail: "",
                FeeNumber: 2,
                FeeNumberSpecified: true,
                FeeType: 6,
                FeeTypeSpecified: true,
                FeeOverride: false,
                FeeOverrideSpecified: true,
                FlightReference: "20220831 Q9 301 ABVLOS",
                Note: "",
                SSRCode: "X15",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                PaymentNumber: 0,
                PaymentNumberSpecified: true,
                ServiceCharges: [
                  {
                    ChargeType: 6,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "XBAG15",
                    TicketCode: "X15",
                    CurrencyCode: "NGN",
                    Amount: 4500,
                    AmountSpecified: true,
                    ChargeDetail: "XBAG 15KG",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 4500,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ChargeType: 5,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "NG",
                    TicketCode: "NG ",
                    CurrencyCode: "NGN",
                    Amount: 225,
                    AmountSpecified: true,
                    ChargeDetail: "ABV-LOS",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 225,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                CreatedDate: "2022-08-30T20:35:05.203Z",
                CreatedDateSpecified: true,
                IsProtected: false,
                IsProtectedSpecified: true,
                FeeApplicationType: 3,
                FeeApplicationTypeSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                FeeCode: "XBAG10",
                FeeDetail: "",
                FeeNumber: 3,
                FeeNumberSpecified: true,
                FeeType: 6,
                FeeTypeSpecified: true,
                FeeOverride: false,
                FeeOverrideSpecified: true,
                FlightReference: "20220831 Q9 301 ABVLOS",
                Note: "",
                SSRCode: "X10",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                PaymentNumber: 0,
                PaymentNumberSpecified: true,
                ServiceCharges: [
                  {
                    ChargeType: 6,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "XBAG10",
                    TicketCode: "X10",
                    CurrencyCode: "NGN",
                    Amount: 8000,
                    AmountSpecified: true,
                    ChargeDetail: "XBAG 10KG",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 8000,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ChargeType: 5,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "NG",
                    TicketCode: "NG ",
                    CurrencyCode: "NGN",
                    Amount: 400,
                    AmountSpecified: true,
                    ChargeDetail: "ABV-LOS",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 400,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                CreatedDate: "2022-08-30T20:35:05.203Z",
                CreatedDateSpecified: true,
                IsProtected: false,
                IsProtectedSpecified: true,
                FeeApplicationType: 3,
                FeeApplicationTypeSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                FeeCode: "SEAT",
                FeeDetail: "",
                FeeNumber: 4,
                FeeNumberSpecified: true,
                FeeType: 9,
                FeeTypeSpecified: true,
                FeeOverride: false,
                FeeOverrideSpecified: true,
                FlightReference: "20220831 Q9 301 ABVLOS",
                Note: "",
                SSRCode: "",
                SSRNumber: 0,
                SSRNumberSpecified: true,
                PaymentNumber: 0,
                PaymentNumberSpecified: true,
                ServiceCharges: [
                  {
                    ChargeType: 6,
                    ChargeTypeSpecified: true,
                    CollectType: 0,
                    CollectTypeSpecified: true,
                    ChargeCode: "SEAT",
                    TicketCode: "STF",
                    CurrencyCode: "NGN",
                    Amount: 0,
                    AmountSpecified: true,
                    ChargeDetail: "ABV-LOS",
                    ForeignCurrencyCode: "NGN",
                    ForeignAmount: 0,
                    ForeignAmountSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                CreatedDate: "2022-08-30T20:35:05.203Z",
                CreatedDateSpecified: true,
                IsProtected: false,
                IsProtectedSpecified: true,
                FeeApplicationType: 3,
                FeeApplicationTypeSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PassengerAddresses: [],
            PassengerTravelDocuments: [],
            PassengerBags: [],
            PassengerID: 51753,
            PassengerIDSpecified: true,
            PassengerTypeInfos: [
              {
                State: 1,
                StateSpecified: true,
                DOB: "9999-12-31T00:00:00Z",
                DOBSpecified: true,
                PaxType: "ADT",
              },
            ],
            PassengerInfos: [
              {
                BalanceDue: 0,
                BalanceDueSpecified: true,
                Gender: 0,
                GenderSpecified: true,
                Nationality: "",
                ResidentCountry: "",
                TotalCost: 64125,
                TotalCostSpecified: true,
                WeightCategory: 1,
                WeightCategorySpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PassengerInfants: [],
            PseudoPassenger: false,
            PseudoPassengerSpecified: true,
            PassengerTypeInfo: {
              State: 1,
              StateSpecified: true,
              DOB: "9999-12-31T00:00:00Z",
              DOBSpecified: true,
              PaxType: "ADT",
            },
            PassengerEMDCouponList: [],
            State: 1,
            StateSpecified: true,
          },
        ],
        Journeys: [
          {
            NotForGeneralUse: false,
            NotForGeneralUseSpecified: true,
            Segments: [
              {
                ActionStatusCode: "HK",
                ArrivalStation: "LOS",
                CabinOfService: "Y",
                ChangeReasonCode: "",
                DepartureStation: "ABV",
                PriorityCode: "",
                SegmentType: "",
                STA: "2022-08-31T09:55:00",
                STASpecified: true,
                STD: "2022-08-31T08:20:00",
                STDSpecified: true,
                International: false,
                InternationalSpecified: true,
                FlightDesignator: {
                  CarrierCode: "Q9",
                  FlightNumber: " 301",
                  OpSuffix: " ",
                },
                XrefFlightDesignator: null,
                Fares: [
                  {
                    ClassOfService: "S",
                    ClassType: "",
                    RuleTariff: "",
                    CarrierCode: "Q9",
                    RuleNumber: "CLSC",
                    FareBasisCode: "SCOW",
                    FareSequence: 2,
                    FareSequenceSpecified: true,
                    FareClassOfService: "S",
                    FareStatus: 0,
                    FareStatusSpecified: true,
                    FareApplicationType: 0,
                    FareApplicationTypeSpecified: true,
                    OriginalClassOfService: "S",
                    XrefClassOfService: "",
                    PaxFares: [
                      {
                        PaxType: "ADT",
                        PaxDiscountCode: "",
                        FareDiscountCode: "",
                        ServiceCharges: [
                          {
                            ChargeType: 0,
                            ChargeTypeSpecified: true,
                            CollectType: 0,
                            CollectTypeSpecified: true,
                            ChargeCode: "",
                            TicketCode: "",
                            CurrencyCode: "NGN",
                            Amount: 33667,
                            AmountSpecified: true,
                            ChargeDetail: "",
                            ForeignCurrencyCode: "NGN",
                            ForeignAmount: 33667,
                            ForeignAmountSpecified: true,
                            State: 1,
                            StateSpecified: true,
                          },
                          {
                            ChargeType: 5,
                            ChargeTypeSpecified: true,
                            CollectType: 0,
                            CollectTypeSpecified: true,
                            ChargeCode: "NG",
                            TicketCode: "NG ",
                            CurrencyCode: "NGN",
                            Amount: 1683,
                            AmountSpecified: true,
                            ChargeDetail: "ABV-LOS",
                            ForeignCurrencyCode: "NGN",
                            ForeignAmount: 1683,
                            ForeignAmountSpecified: true,
                            State: 1,
                            StateSpecified: true,
                          },
                          {
                            ChargeType: 4,
                            ChargeTypeSpecified: true,
                            CollectType: 0,
                            CollectTypeSpecified: true,
                            ChargeCode: "YQ",
                            TicketCode: "YQ",
                            CurrencyCode: "NGN",
                            Amount: 3000,
                            AmountSpecified: true,
                            ChargeDetail: "ABV-LOS",
                            ForeignCurrencyCode: "NGN",
                            ForeignAmount: 3000,
                            ForeignAmountSpecified: true,
                            State: 1,
                            StateSpecified: true,
                          },
                          {
                            ChargeType: 5,
                            ChargeTypeSpecified: true,
                            CollectType: 0,
                            CollectTypeSpecified: true,
                            ChargeCode: "NG",
                            TicketCode: "NG ",
                            CurrencyCode: "NGN",
                            Amount: 150,
                            AmountSpecified: true,
                            ChargeDetail: "ABV-LOS",
                            ForeignCurrencyCode: "NGN",
                            ForeignAmount: 150,
                            ForeignAmountSpecified: true,
                            State: 1,
                            StateSpecified: true,
                          },
                          {
                            ChargeType: 4,
                            ChargeTypeSpecified: true,
                            CollectType: 0,
                            CollectTypeSpecified: true,
                            ChargeCode: "QT",
                            TicketCode: "QT",
                            CurrencyCode: "NGN",
                            Amount: 2000,
                            AmountSpecified: true,
                            ChargeDetail: "ABV-LOS",
                            ForeignCurrencyCode: "NGN",
                            ForeignAmount: 2000,
                            ForeignAmountSpecified: true,
                            State: 1,
                            StateSpecified: true,
                          },
                        ],
                        TicketFareBasisCode: "SCOW",
                        ProofOfStatusRequired: false,
                        ProofOfStatusRequiredSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                    ],
                    ProductClass: "GC",
                    IsAllotmentMarketFare: false,
                    IsAllotmentMarketFareSpecified: true,
                    TravelClassCode: "Y",
                    FareSellKey: "0~S~~Q9~SCOW~CLSC~~4~2~NABVLOS0040020~X",
                    InboundOutbound: 0,
                    InboundOutboundSpecified: true,
                    FareLink: 4,
                    FareLinkSpecified: true,
                    FareDesignator: {
                      FareTypeIndicator: "N",
                      CityCode: "ABV",
                      TravelCityCode: "LOS",
                      RuleFareTypeCode: "",
                      BaseFareFareClassCode: "",
                      DowType: "",
                      SeasonType: "",
                      RoutingNumber: 0,
                      RoutingNumberSpecified: true,
                      OneWayRoundTrip: "",
                      OpenJawAllowed: false,
                      OpenJawAllowedSpecified: true,
                      TripDirection: "",
                      FareByRuleAccountCode: "",
                    },
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                Legs: [
                  {
                    ArrivalStation: "LOS",
                    DepartureStation: "ABV",
                    STA: "2022-08-31T09:55:00",
                    STASpecified: true,
                    STD: "2022-08-31T08:20:00",
                    STDSpecified: true,
                    FlightDesignator: {
                      CarrierCode: "Q9",
                      FlightNumber: " 301",
                      OpSuffix: " ",
                    },
                    LegInfo: {
                      AdjustedCapacity: 70,
                      AdjustedCapacitySpecified: true,
                      EquipmentType: "AT7",
                      EquipmentTypeSuffix: "",
                      ArrivalTerminal: "",
                      ArrvLTV: 60,
                      ArrvLTVSpecified: true,
                      Capacity: 70,
                      CapacitySpecified: true,
                      CodeShareIndicator: " ",
                      DepartureTerminal: "",
                      DeptLTV: 60,
                      DeptLTVSpecified: true,
                      ETicket: false,
                      ETicketSpecified: true,
                      FlifoUpdated: false,
                      FlifoUpdatedSpecified: true,
                      IROP: false,
                      IROPSpecified: true,
                      Status: 0,
                      StatusSpecified: true,
                      Lid: 70,
                      LidSpecified: true,
                      OnTime: " ",
                      PaxSTA: "2022-08-30T20:36:15.6079195",
                      PaxSTASpecified: true,
                      PaxSTD: "2022-08-30T20:36:15.6079195",
                      PaxSTDSpecified: true,
                      PRBCCode: "Y68",
                      ScheduleServiceType: " ",
                      Sold: 1,
                      SoldSpecified: true,
                      OutMoveDays: 365,
                      OutMoveDaysSpecified: true,
                      BackMoveDays: 365,
                      BackMoveDaysSpecified: true,
                      LegNests: [],
                      LegSSRs: [],
                      OperatingFlightNumber: "    ",
                      OperatedByText: "",
                      OperatingCarrier: "",
                      OperatingOpSuffix: " ",
                      SubjectToGovtApproval: false,
                      SubjectToGovtApprovalSpecified: true,
                      MarketingCode: "",
                      ChangeOfDirection: false,
                      ChangeOfDirectionSpecified: true,
                      MarketingOverride: false,
                      MarketingOverrideSpecified: true,
                      AircraftOwner: "",
                      State: 1,
                      StateSpecified: true,
                    },
                    OperationsInfo: {
                      ActualArrivalGate: "",
                      ActualDepartureGate: "",
                      ActualOffBlockTime: "9999-12-31T00:00:00Z",
                      ActualOffBlockTimeSpecified: true,
                      ActualOnBlockTime: "9999-12-31T00:00:00Z",
                      ActualOnBlockTimeSpecified: true,
                      ActualTouchDownTime: "9999-12-31T00:00:00Z",
                      ActualTouchDownTimeSpecified: true,
                      AirborneTime: "9999-12-31T00:00:00Z",
                      AirborneTimeSpecified: true,
                      ArrivalGate: "",
                      ArrivalNote: "",
                      ArrivalStatus: 0,
                      ArrivalStatusSpecified: true,
                      BaggageClaim: "",
                      DepartureGate: "",
                      DepartureNote: "",
                      DepartureStatus: 0,
                      DepartureStatusSpecified: true,
                      ETA: "9999-12-31T00:00:00Z",
                      ETASpecified: true,
                      ETD: "9999-12-31T00:00:00Z",
                      ETDSpecified: true,
                      STA: "2022-08-31T09:55:00",
                      STASpecified: true,
                      STD: "2022-08-31T08:20:00",
                      STDSpecified: true,
                      TailNumber: "",
                      State: 0,
                      StateSpecified: true,
                    },
                    InventoryLegID: 14759,
                    InventoryLegIDSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                PaxBags: [],
                PaxSeats: [
                  {
                    PassengerNumber: 0,
                    PassengerNumberSpecified: true,
                    ArrivalStation: "LOS",
                    DepartureStation: "ABV",
                    UnitDesignator: "11C",
                    CompartmentDesignator: "Y",
                    SeatPreference: 3,
                    SeatPreferenceSpecified: true,
                    Penalty: 0,
                    PenaltySpecified: true,
                    SeatTogetherPreference: false,
                    SeatTogetherPreferenceSpecified: true,
                    PaxSeatInfo: {
                      SeatSet: 22,
                      SeatSetSpecified: true,
                      Deck: 1,
                      DeckSpecified: true,
                      Properties: [
                        {
                          key: "SRVZONE",
                          value: "2",
                        },
                        {
                          key: "AISLE",
                          value: "TRUE",
                        },
                        {
                          key: "INFANT",
                          value: "TRUE",
                        },
                        {
                          key: "TCC",
                          value: "Y",
                        },
                      ],
                    },
                    SeatStatusCode: "",
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                PaxSSRs: [
                  {
                    ActionStatusCode: "HK",
                    ArrivalStation: "LOS",
                    DepartureStation: "ABV",
                    PassengerNumber: 0,
                    PassengerNumberSpecified: true,
                    SSRCode: "X10",
                    SSRNumber: 1,
                    SSRNumberSpecified: true,
                    SSRDetail: "",
                    FeeCode: "XBAG10",
                    Note: "",
                    SSRValue: 1,
                    SSRValueSpecified: true,
                    IsInServiceBundle: false,
                    IsInServiceBundleSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ActionStatusCode: "HK",
                    ArrivalStation: "LOS",
                    DepartureStation: "ABV",
                    PassengerNumber: 0,
                    PassengerNumberSpecified: true,
                    SSRCode: "X15",
                    SSRNumber: 1,
                    SSRNumberSpecified: true,
                    SSRDetail: "",
                    FeeCode: "XBAG15",
                    Note: "",
                    SSRValue: 1,
                    SSRValueSpecified: true,
                    IsInServiceBundle: false,
                    IsInServiceBundleSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ActionStatusCode: "HK",
                    ArrivalStation: "LOS",
                    DepartureStation: "ABV",
                    PassengerNumber: 0,
                    PassengerNumberSpecified: true,
                    SSRCode: "X20",
                    SSRNumber: 1,
                    SSRNumberSpecified: true,
                    SSRDetail: "",
                    FeeCode: "XBAG20",
                    Note: "",
                    SSRValue: 1,
                    SSRValueSpecified: true,
                    IsInServiceBundle: false,
                    IsInServiceBundleSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                  {
                    ActionStatusCode: "HK",
                    ArrivalStation: "LOS",
                    DepartureStation: "ABV",
                    PassengerNumber: 0,
                    PassengerNumberSpecified: true,
                    SSRCode: "X20",
                    SSRNumber: 2,
                    SSRNumberSpecified: true,
                    SSRDetail: "",
                    FeeCode: "XBAG20",
                    Note: "",
                    SSRValue: 1,
                    SSRValueSpecified: true,
                    IsInServiceBundle: false,
                    IsInServiceBundleSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                PaxSegments: [
                  {
                    BoardingSequence: "0",
                    CreatedDate: "2022-08-30T20:35:05.203Z",
                    CreatedDateSpecified: true,
                    LiftStatus: 0,
                    LiftStatusSpecified: true,
                    OverBookIndicator: "",
                    PassengerNumber: 0,
                    PassengerNumberSpecified: true,
                    PriorityDate: "2022-08-30T20:35:05.32Z",
                    PriorityDateSpecified: true,
                    TripType: 1,
                    TripTypeSpecified: true,
                    TimeChanged: false,
                    TimeChangedSpecified: true,
                    POS: {
                      AgentCode: "WebAnonymous1",
                      OrganizationCode: "Q9",
                      DomainCode: "WW2",
                      LocationCode: "WWW",
                      State: 1,
                      StateSpecified: true,
                    },
                    SourcePOS: {
                      AgentCode: "WebAnonymous1",
                      OrganizationCode: "Q9",
                      DomainCode: "WW2",
                      LocationCode: "WWW",
                      State: 1,
                      StateSpecified: true,
                    },
                    VerifiedTravelDocs: "",
                    ModifiedDate: "2022-08-30T20:35:05.203Z",
                    ModifiedDateSpecified: true,
                    ActivityDate: "2022-08-30T20:35:05.203Z",
                    ActivityDateSpecified: true,
                    BaggageAllowanceWeight: 0,
                    BaggageAllowanceWeightSpecified: true,
                    BaggageAllowanceWeightType: 0,
                    BaggageAllowanceWeightTypeSpecified: true,
                    BaggageAllowanceUsed: false,
                    BaggageAllowanceUsedSpecified: true,
                    ReferenceNumber: 0,
                    ReferenceNumberSpecified: true,
                    BoardingPassDetail: null,
                    ServiceBundleCode: "",
                    BaggageGroupNumber: 0,
                    BaggageGroupNumberSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                PaxTickets: [],
                PaxSeatPreferences: null,
                SalesDate: "2022-08-30T20:35:05.203Z",
                SalesDateSpecified: true,
                SegmentSellKey:
                  "Q9~ 301~ ~~ABV~08/31/2022 08:20~LOS~08/31/2022 09:55~~",
                PaxScores: [],
                ChannelType: 4,
                ChannelTypeSpecified: true,
                AvailabilitySourceCode: "",
                InventorySourceCode: "",
                State: 1,
                StateSpecified: true,
              },
            ],
            JourneySellKey:
              "Q9~ 301~ ~~ABV~08/31/2022 08:20~LOS~08/31/2022 09:55~~",
            PackageIndicator: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        BookingComments: [],
        BookingQueueInfos: [],
        BookingContacts: [
          {
            TypeCode: "P",
            Names: [
              {
                FirstName: "olabamipe",
                MiddleName: "olabamipe",
                LastName: "Olabamipe",
                Suffix: "",
                Title: "MRS",
                State: 1,
                StateSpecified: true,
              },
            ],
            EmailAddress: "teeola48@gmail.com",
            HomePhone: "9089675668",
            WorkPhone: "9089675668",
            OtherPhone: "9089675668",
            Fax: "",
            CompanyName: "GreenAfrica",
            AddressLine1: "Lagos",
            AddressLine2: "",
            AddressLine3: "",
            City: "Lagos",
            ProvinceState: "LA",
            PostalCode: "",
            CountryCode: "NG",
            CultureCode: "",
            DistributionOption: 2,
            DistributionOptionSpecified: true,
            CustomerNumber: "",
            NotificationPreference: 0,
            NotificationPreferenceSpecified: true,
            SourceOrganization: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        Payments: [
          {
            ReferenceType: 1,
            ReferenceTypeSpecified: true,
            ReferenceID: 38413,
            ReferenceIDSpecified: true,
            PaymentMethodType: 0,
            PaymentMethodTypeSpecified: true,
            PaymentMethodCode: "PS",
            CurrencyCode: "NGN",
            PaymentAmount: 64125,
            PaymentAmountSpecified: true,
            CollectedCurrencyCode: "NGN",
            CollectedAmount: 64125,
            CollectedAmountSpecified: true,
            QuotedCurrencyCode: "NGN",
            QuotedAmount: 64125,
            QuotedAmountSpecified: true,
            Status: 3,
            StatusSpecified: true,
            AccountNumber: "",
            AccountNumberID: 0,
            AccountNumberIDSpecified: true,
            Expiration: "9999-12-31T00:00:00Z",
            ExpirationSpecified: true,
            AuthorizationCode: "",
            AuthorizationStatus: 4,
            AuthorizationStatusSpecified: true,
            ParentPaymentID: 0,
            ParentPaymentIDSpecified: true,
            Transferred: false,
            TransferredSpecified: true,
            ReconcilliationID: 0,
            ReconcilliationIDSpecified: true,
            FundedDate: "1800-01-01T00:00:00Z",
            FundedDateSpecified: true,
            Installments: 0,
            InstallmentsSpecified: true,
            PaymentText: "",
            ChannelType: 4,
            ChannelTypeSpecified: true,
            PaymentNumber: 1,
            PaymentNumberSpecified: true,
            AccountName: "",
            SourcePointOfSale: {
              AgentCode: "WebAnonymous1",
              OrganizationCode: "Q9",
              DomainCode: "WW2",
              LocationCode: "WWW",
              State: 1,
              StateSpecified: true,
            },
            PointOfSale: {
              AgentCode: "WebAnonymous1",
              OrganizationCode: "Q9",
              DomainCode: "WW2",
              LocationCode: "WWW",
              State: 1,
              StateSpecified: true,
            },
            PaymentID: 51702,
            PaymentIDSpecified: true,
            Deposit: false,
            DepositSpecified: true,
            AccountID: 0,
            AccountIDSpecified: true,
            Password: "",
            AccountTransactionCode: "",
            VoucherID: 0,
            VoucherIDSpecified: true,
            VoucherTransactionID: 0,
            VoucherTransactionIDSpecified: true,
            OverrideVoucherRestrictions: false,
            OverrideVoucherRestrictionsSpecified: true,
            OverrideAmount: false,
            OverrideAmountSpecified: true,
            RecordLocator: "",
            PaymentAddedToState: true,
            PaymentAddedToStateSpecified: true,
            DCC: {
              DCCRateID: "00000000-0000-0000-0000-000000000000",
              DCCStatus: 0,
              DCCStatusSpecified: true,
              ValidationDCCApplicable: false,
              ValidationDCCApplicableSpecified: true,
              ValidationDCCRateValue: 0,
              ValidationDCCRateValueSpecified: true,
              ValidationDCCCurrency: "",
              ValidationDCCAmount: 0,
              ValidationDCCAmountSpecified: true,
              ValidationDCCPutInState: "",
            },
            ThreeDSecure: {
              BrowserUserAgent: "",
              BrowserAccept: "",
              RemoteIpAddress: "",
              TermUrl: "",
              ProxyVia: "",
              ValidationTDSApplicable: false,
              ValidationTDSApplicableSpecified: true,
              ValidationTDSPaReq: "",
              ValidationTDSAcsUrl: "",
              ValidationTDSPaRes: "",
              ValidationTDSSuccessful: false,
              ValidationTDSSuccessfulSpecified: true,
              ValidationTDSAuthResult: "",
              ValidationTDSCavv: "",
              ValidationTDSCavvAlgorithm: "",
              ValidationTDSEci: "",
              ValidationTDSXid: "",
            },
            PaymentFields: [
              {
                FieldName: "REF",
                FieldValue: "U3RZRVDUGOSPHMGEWCBG1VLBNE",
              },
            ],
            PaymentAddresses: [],
            CreatedDate: "2022-08-30T20:36:13.037Z",
            CreatedDateSpecified: true,
            CreatedAgentID: 409,
            CreatedAgentIDSpecified: true,
            ModifiedDate: "2022-08-30T20:36:13.037Z",
            ModifiedDateSpecified: true,
            ModifiedAgentID: 409,
            ModifiedAgentIDSpecified: true,
            BinRange: 0,
            BinRangeSpecified: true,
            ApprovalDate: "2022-08-30T20:36:13.09Z",
            ApprovalDateSpecified: true,
            BookingID: 38413,
            BookingIDSpecified: true,
            State: 1,
            StateSpecified: true,
          },
        ],
        BookingComponents: [],
        NumericRecordLocator: "062435163508",
        SourceBookingPOS: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          ISOCountryCode: "",
          SourceSystemCode: "",
          State: 1,
          StateSpecified: true,
        },
        ReissueCount: 0,
        ReissueCountSpecified: true,
        PricingReissueMode: "16",
        BaggagePricingSystemCode: "1N",
        BaggageAllowanceInfo: null,
        BaggageAllowanceList: [],
        OtherServiceInfoList: [],
      },
    },
    seatAvailability: null,
    seatResponseLoading: true,
    SSRAvailabilityLoading: false,
    SSRAvailabilityResponse: null,
    sellSSRLoading: false,
    sellSSRResponse: null,
    assignSeatResponse: null,
    bookingState: null,
    sessionStateLoading: false,
    sessionStateResponse: {
      Error: null,
      BookingData: {
        State: 0,
        StateSpecified: true,
        RecordLocator: "",
        CurrencyCode: "",
        PaxCount: 0,
        PaxCountSpecified: true,
        SystemCode: "",
        BookingID: 0,
        BookingIDSpecified: true,
        BookingParentID: 0,
        BookingParentIDSpecified: true,
        ParentRecordLocator: "",
        BookingChangeCode: "",
        GroupName: "",
        BookingInfo: {
          BookingStatus: 0,
          BookingStatusSpecified: true,
          BookingType: "",
          ChannelType: 0,
          ChannelTypeSpecified: true,
          CreatedDate: "9999-12-31T00:00:00Z",
          CreatedDateSpecified: true,
          ExpiredDate: "9999-12-31T00:00:00Z",
          ExpiredDateSpecified: true,
          ModifiedDate: "9999-12-31T00:00:00Z",
          ModifiedDateSpecified: true,
          PriceStatus: 2,
          PriceStatusSpecified: true,
          ProfileStatus: 0,
          ProfileStatusSpecified: true,
          ChangeAllowed: true,
          ChangeAllowedSpecified: true,
          CreatedAgentID: 0,
          CreatedAgentIDSpecified: true,
          ModifiedAgentID: 0,
          ModifiedAgentIDSpecified: true,
          BookingDate: "2022-08-30T20:36:16.2329295Z",
          BookingDateSpecified: true,
          OwningCarrierCode: "",
          PaidStatus: 0,
          PaidStatusSpecified: true,
          ActivityDate: "9999-12-31T00:00:00Z",
          ActivityDateSpecified: true,
          State: 0,
          StateSpecified: true,
        },
        POS: null,
        SourcePOS: null,
        TypeOfSale: null,
        BookingHold: null,
        BookingSum: {
          BalanceDue: 0,
          BalanceDueSpecified: true,
          AuthorizedBalanceDue: 0,
          AuthorizedBalanceDueSpecified: true,
          SegmentCount: 0,
          SegmentCountSpecified: true,
          PassiveSegmentCount: 0,
          PassiveSegmentCountSpecified: true,
          TotalCost: 0,
          TotalCostSpecified: true,
          PointsBalanceDue: 0,
          PointsBalanceDueSpecified: true,
          TotalPointCost: 0,
          TotalPointCostSpecified: true,
          AlternateCurrencyCode: "",
          AlternateCurrencyBalanceDue: 0,
          AlternateCurrencyBalanceDueSpecified: true,
        },
        ReceivedBy: null,
        RecordLocators: [],
        Passengers: [],
        Journeys: [],
        BookingComments: [],
        BookingQueueInfos: [],
        BookingContacts: [],
        Payments: [],
        BookingComponents: [],
        NumericRecordLocator: "",
        SourceBookingPOS: null,
        ReissueCount: 0,
        ReissueCountSpecified: true,
        PricingReissueMode: "16",
        BaggagePricingSystemCode: "1N",
        BaggageAllowanceInfo: null,
        BaggageAllowanceList: [],
        OtherServiceInfoList: [],
      },
    },
  },
  payment: {
    gatewaysLoading: false,
    gatewaysResponse: null,
    paymentLoading: false,
    paymentResponse: null,
    verifyPaymentLoading: false,
    verifyPaymentResponse: {
      success: true,
      code: 0,
      locale: "en",
      message: "OK",
      data: {
        message: "Payment Successful",
        pnr: "U3RZRV",
      },
    },
  },
  booking: {
    flightParams: null,
    flightAvailabilityLoading: false,
    availabilityResponse: null,
  },
  _persist: {
    version: 1,
    rehydrated: true,
  },
};
