export const bookingResponse = {
  Error: null,
  Booking: {
    State: 1,
    StateSpecified: true,
    RecordLocator: "U4UJ4P",
    CurrencyCode: "NGN",
    PaxCount: 1,
    PaxCountSpecified: true,
    SystemCode: "",
    BookingID: 39084,
    BookingIDSpecified: true,
    BookingParentID: 0,
    BookingParentIDSpecified: true,
    ParentRecordLocator: "",
    BookingChangeCode: "",
    GroupName: "",
    BookingInfo: {
      BookingStatus: 2,
      BookingStatusSpecified: true,
      BookingType: "",
      ChannelType: 4,
      ChannelTypeSpecified: true,
      CreatedDate: "2022-10-06T11:08:55.94Z",
      CreatedDateSpecified: true,
      ExpiredDate: "2022-10-16T20:20:00Z",
      ExpiredDateSpecified: true,
      ModifiedDate: "2022-10-06T11:09:39.22Z",
      ModifiedDateSpecified: true,
      PriceStatus: 2,
      PriceStatusSpecified: true,
      ProfileStatus: 1,
      ProfileStatusSpecified: true,
      ChangeAllowed: true,
      ChangeAllowedSpecified: true,
      CreatedAgentID: 409,
      CreatedAgentIDSpecified: true,
      ModifiedAgentID: 409,
      ModifiedAgentIDSpecified: true,
      BookingDate: "2022-10-06T11:08:55.94Z",
      BookingDateSpecified: true,
      OwningCarrierCode: "Q9",
      PaidStatus: 1,
      PaidStatusSpecified: true,
      ActivityDate: "2022-10-06T11:09:39.22",
      ActivityDateSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    POS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    SourcePOS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    TypeOfSale: {
      PaxResidentCountry: "NG",
      PromotionCode: "",
      FareTypes: [],
      PromotionSold: false,
      PromotionSoldSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    BookingHold: {
      HoldDateTime: "9999-12-31T00:00:00Z",
      HoldDateTimeSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    BookingSum: {
      BalanceDue: 0,
      BalanceDueSpecified: true,
      AuthorizedBalanceDue: 0,
      AuthorizedBalanceDueSpecified: true,
      SegmentCount: 2,
      SegmentCountSpecified: true,
      PassiveSegmentCount: 0,
      PassiveSegmentCountSpecified: true,
      TotalCost: 135302,
      TotalCostSpecified: true,
      PointsBalanceDue: 0,
      PointsBalanceDueSpecified: true,
      TotalPointCost: 0,
      TotalPointCostSpecified: true,
      AlternateCurrencyCode: "",
      AlternateCurrencyBalanceDue: 0,
      AlternateCurrencyBalanceDueSpecified: true,
    },
    ReceivedBy: {
      ReceivedBy: "",
      ReceivedReference: "",
      ReferralCode: "",
      LatestReceivedBy: "",
      LatestReceivedReference: "",
      State: 1,
      StateSpecified: true,
    },
    RecordLocators: [],
    Passengers: [
      {
        PassengerPrograms: null,
        CustomerNumber: "",
        PassengerNumber: 0,
        PassengerNumberSpecified: true,
        FamilyNumber: 0,
        FamilyNumberSpecified: true,
        PaxDiscountCode: "",
        Names: [
          {
            FirstName: "olabamipe",
            MiddleName: "",
            LastName: "ytee",
            Suffix: "",
            Title: "MR",
            State: 1,
            StateSpecified: true,
          },
        ],
        Infant: null,
        PassengerInfo: {
          BalanceDue: 0,
          BalanceDueSpecified: true,
          Gender: 0,
          GenderSpecified: true,
          Nationality: "",
          ResidentCountry: "",
          TotalCost: 135302,
          TotalCostSpecified: true,
          WeightCategory: 0,
          WeightCategorySpecified: true,
          State: 1,
          StateSpecified: true,
        },
        PassengerProgram: {
          ProgramCode: "",
          ProgramLevelCode: "",
          ProgramNumber: "",
          State: 1,
          StateSpecified: true,
        },
        PassengerFees: [
          {
            ActionStatusCode: "HK",
            FeeCode: "CLSC",
            FeeDetail: "",
            FeeNumber: 0,
            FeeNumberSpecified: true,
            FeeType: 17,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221012 Q9 300 LOSABV",
            Note: "",
            SSRCode: "",
            SSRNumber: 0,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "CLSC",
                TicketCode: "CLS",
                CurrencyCode: "NGN",
                Amount: 0,
                AmountSpecified: true,
                ChargeDetail: "Classic",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 0,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-06T11:08:55.94Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 2,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "CLSC",
            FeeDetail: "",
            FeeNumber: 1,
            FeeNumberSpecified: true,
            FeeType: 17,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221015 Q9 303 ABVLOS",
            Note: "",
            SSRCode: "",
            SSRNumber: 0,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "CLSC",
                TicketCode: "CLS",
                CurrencyCode: "NGN",
                Amount: 0,
                AmountSpecified: true,
                ChargeDetail: "Classic",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 0,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-06T11:08:55.94Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 2,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "XBAG20",
            FeeDetail: "",
            FeeNumber: 2,
            FeeNumberSpecified: true,
            FeeType: 6,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221012 Q9 300 LOSABV",
            Note: "",
            SSRCode: "X20",
            SSRNumber: 1,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "XBAG20",
                TicketCode: "X20",
                CurrencyCode: "NGN",
                Amount: 11429,
                AmountSpecified: true,
                ChargeDetail: "XBAG 20KG",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 11429,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ChargeType: 5,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "NG",
                TicketCode: "NG ",
                CurrencyCode: "NGN",
                Amount: 571,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 571,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-06T11:08:55.94Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "XBAG20",
            FeeDetail: "",
            FeeNumber: 3,
            FeeNumberSpecified: true,
            FeeType: 6,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221015 Q9 303 ABVLOS",
            Note: "",
            SSRCode: "X20",
            SSRNumber: 1,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "XBAG20",
                TicketCode: "X20",
                CurrencyCode: "NGN",
                Amount: 11429,
                AmountSpecified: true,
                ChargeDetail: "XBAG 20KG",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 11429,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ChargeType: 5,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "NG",
                TicketCode: "NG ",
                CurrencyCode: "NGN",
                Amount: 571,
                AmountSpecified: true,
                ChargeDetail: "ABV-LOS",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 571,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-06T11:08:55.94Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "SEAT",
            FeeDetail: "",
            FeeNumber: 4,
            FeeNumberSpecified: true,
            FeeType: 9,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221012 Q9 300 LOSABV",
            Note: "",
            SSRCode: "",
            SSRNumber: 0,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "SEAT",
                TicketCode: "STF",
                CurrencyCode: "NGN",
                Amount: 2000,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 2000,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-06T11:08:55.94Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "SEAT",
            FeeDetail: "",
            FeeNumber: 5,
            FeeNumberSpecified: true,
            FeeType: 9,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221015 Q9 303 ABVLOS",
            Note: "",
            SSRCode: "",
            SSRNumber: 0,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "SEAT",
                TicketCode: "STF",
                CurrencyCode: "NGN",
                Amount: 2000,
                AmountSpecified: true,
                ChargeDetail: "ABV-LOS",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 2000,
                ForeignAmountSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-06T11:08:55.94Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
        ],
        PassengerAddresses: [],
        PassengerTravelDocuments: [],
        PassengerBags: [],
        PassengerID: 52633,
        PassengerIDSpecified: true,
        PassengerTypeInfos: [
          {
            State: 1,
            StateSpecified: true,
            DOB: "9999-12-31T00:00:00Z",
            DOBSpecified: true,
            PaxType: "ADT",
          },
        ],
        PassengerInfos: [
          {
            BalanceDue: 0,
            BalanceDueSpecified: true,
            Gender: 0,
            GenderSpecified: true,
            Nationality: "",
            ResidentCountry: "",
            TotalCost: 135302,
            TotalCostSpecified: true,
            WeightCategory: 0,
            WeightCategorySpecified: true,
            State: 1,
            StateSpecified: true,
          },
        ],
        PassengerInfants: [],
        PseudoPassenger: false,
        PseudoPassengerSpecified: true,
        PassengerTypeInfo: {
          State: 1,
          StateSpecified: true,
          DOB: "9999-12-31T00:00:00Z",
          DOBSpecified: true,
          PaxType: "ADT",
        },
        PassengerEMDCouponList: [],
        State: 1,
        StateSpecified: true,
      },
    ],
    Journeys: [
      {
        NotForGeneralUse: false,
        NotForGeneralUseSpecified: true,
        Segments: [
          {
            ActionStatusCode: "HK",
            ArrivalStation: "ABV",
            CabinOfService: "Y",
            ChangeReasonCode: "",
            DepartureStation: "LOS",
            PriorityCode: "",
            SegmentType: "",
            STA: "2022-10-12T07:30:00",
            STASpecified: true,
            STD: "2022-10-12T05:50:00",
            STDSpecified: true,
            International: false,
            InternationalSpecified: true,
            FlightDesignator: {
              CarrierCode: "Q9",
              FlightNumber: " 300",
              OpSuffix: " ",
            },
            XrefFlightDesignator: null,
            Fares: [
              {
                ClassOfService: "W",
                ClassType: "",
                RuleTariff: "",
                CarrierCode: "Q9",
                RuleNumber: "CLSC",
                FareBasisCode: "WCOW",
                FareSequence: 1,
                FareSequenceSpecified: true,
                FareClassOfService: "W",
                FareStatus: 0,
                FareStatusSpecified: true,
                FareApplicationType: 0,
                FareApplicationTypeSpecified: true,
                OriginalClassOfService: "W",
                XrefClassOfService: "",
                PaxFares: [
                  {
                    PaxType: "ADT",
                    PaxDiscountCode: "",
                    FareDiscountCode: "",
                    ServiceCharges: [
                      {
                        ChargeType: 0,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "",
                        TicketCode: "",
                        CurrencyCode: "NGN",
                        Amount: 46191,
                        AmountSpecified: true,
                        ChargeDetail: "",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 46191,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 2310,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2310,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "YQ",
                        TicketCode: "YQ",
                        CurrencyCode: "NGN",
                        Amount: 3000,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 3000,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 150,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 150,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "QT",
                        TicketCode: "QT",
                        CurrencyCode: "NGN",
                        Amount: 2000,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2000,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                    ],
                    TicketFareBasisCode: "WCOW",
                    ProofOfStatusRequired: false,
                    ProofOfStatusRequiredSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                ProductClass: "GC",
                IsAllotmentMarketFare: false,
                IsAllotmentMarketFareSpecified: true,
                TravelClassCode: "Y",
                FareSellKey: "0~W~~Q9~WCOW~CLSC~~6~1~NABVLOS0060010~X",
                InboundOutbound: 0,
                InboundOutboundSpecified: true,
                FareLink: 6,
                FareLinkSpecified: true,
                FareDesignator: {
                  FareTypeIndicator: "N",
                  CityCode: "ABV",
                  TravelCityCode: "LOS",
                  RuleFareTypeCode: "",
                  BaseFareFareClassCode: "",
                  DowType: "",
                  SeasonType: "",
                  RoutingNumber: 0,
                  RoutingNumberSpecified: true,
                  OneWayRoundTrip: "",
                  OpenJawAllowed: false,
                  OpenJawAllowedSpecified: true,
                  TripDirection: "",
                  FareByRuleAccountCode: "",
                },
                State: 1,
                StateSpecified: true,
              },
            ],
            Legs: [
              {
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                STA: "2022-10-12T07:30:00",
                STASpecified: true,
                STD: "2022-10-12T05:50:00",
                STDSpecified: true,
                FlightDesignator: {
                  CarrierCode: "Q9",
                  FlightNumber: " 300",
                  OpSuffix: " ",
                },
                LegInfo: {
                  AdjustedCapacity: 70,
                  AdjustedCapacitySpecified: true,
                  EquipmentType: "AT7",
                  EquipmentTypeSuffix: "",
                  ArrivalTerminal: "",
                  ArrvLTV: 60,
                  ArrvLTVSpecified: true,
                  Capacity: 70,
                  CapacitySpecified: true,
                  CodeShareIndicator: " ",
                  DepartureTerminal: "",
                  DeptLTV: 60,
                  DeptLTVSpecified: true,
                  ETicket: false,
                  ETicketSpecified: true,
                  FlifoUpdated: false,
                  FlifoUpdatedSpecified: true,
                  IROP: false,
                  IROPSpecified: true,
                  Status: 0,
                  StatusSpecified: true,
                  Lid: 70,
                  LidSpecified: true,
                  OnTime: " ",
                  PaxSTA: "2022-10-06T11:11:06.1659352",
                  PaxSTASpecified: true,
                  PaxSTD: "2022-10-06T11:11:06.1659352",
                  PaxSTDSpecified: true,
                  PRBCCode: "Y68",
                  ScheduleServiceType: " ",
                  Sold: 6,
                  SoldSpecified: true,
                  OutMoveDays: 365,
                  OutMoveDaysSpecified: true,
                  BackMoveDays: 365,
                  BackMoveDaysSpecified: true,
                  LegNests: [],
                  LegSSRs: [],
                  OperatingFlightNumber: "    ",
                  OperatedByText: "",
                  OperatingCarrier: "",
                  OperatingOpSuffix: " ",
                  SubjectToGovtApproval: false,
                  SubjectToGovtApprovalSpecified: true,
                  MarketingCode: "",
                  ChangeOfDirection: false,
                  ChangeOfDirectionSpecified: true,
                  MarketingOverride: false,
                  MarketingOverrideSpecified: true,
                  AircraftOwner: "",
                  State: 1,
                  StateSpecified: true,
                },
                OperationsInfo: null,
                InventoryLegID: 14590,
                InventoryLegIDSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxBags: [],
            PaxSeats: [
              {
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                UnitDesignator: "2A",
                CompartmentDesignator: "Y",
                SeatPreference: 3,
                SeatPreferenceSpecified: true,
                Penalty: 0,
                PenaltySpecified: true,
                SeatTogetherPreference: false,
                SeatTogetherPreferenceSpecified: true,
                PaxSeatInfo: {
                  SeatSet: 3,
                  SeatSetSpecified: true,
                  Deck: 1,
                  DeckSpecified: true,
                  Properties: [
                    {
                      key: "SRVZONE",
                      value: "1",
                    },
                    {
                      key: "WINDOW",
                      value: "TRUE",
                    },
                    {
                      key: "INFANT",
                      value: "TRUE",
                    },
                    {
                      key: "TCC",
                      value: "Y",
                    },
                  ],
                },
                SeatStatusCode: "",
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxSSRs: [
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "I15",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "IBAG15",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: true,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "X20",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "XBAG20",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: false,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxSegments: [
              {
                BoardingSequence: "0",
                CreatedDate: "2022-10-06T11:08:55.94Z",
                CreatedDateSpecified: true,
                LiftStatus: 0,
                LiftStatusSpecified: true,
                OverBookIndicator: "",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                PriorityDate: "2022-10-06T11:08:55.97Z",
                PriorityDateSpecified: true,
                TripType: 1,
                TripTypeSpecified: true,
                TimeChanged: false,
                TimeChangedSpecified: true,
                POS: {
                  AgentCode: "WebAnonymous1",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                SourcePOS: {
                  AgentCode: "WebAnonymous1",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                VerifiedTravelDocs: "",
                ModifiedDate: "2022-10-06T11:08:55.94Z",
                ModifiedDateSpecified: true,
                ActivityDate: "2022-10-06T11:08:55.94Z",
                ActivityDateSpecified: true,
                BaggageAllowanceWeight: 0,
                BaggageAllowanceWeightSpecified: true,
                BaggageAllowanceWeightType: 0,
                BaggageAllowanceWeightTypeSpecified: true,
                BaggageAllowanceUsed: false,
                BaggageAllowanceUsedSpecified: true,
                ReferenceNumber: 0,
                ReferenceNumberSpecified: true,
                BoardingPassDetail: null,
                ServiceBundleCode: "CLSC",
                BaggageGroupNumber: 0,
                BaggageGroupNumberSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxTickets: [],
            PaxSeatPreferences: null,
            SalesDate: "2022-10-06T11:08:55.94Z",
            SalesDateSpecified: true,
            SegmentSellKey:
              "Q9~ 300~ ~~LOS~10/12/2022 05:50~ABV~10/12/2022 07:30~~",
            PaxScores: [],
            ChannelType: 4,
            ChannelTypeSpecified: true,
            AvailabilitySourceCode: "",
            InventorySourceCode: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        JourneySellKey:
          "Q9~ 300~ ~~LOS~10/12/2022 05:50~ABV~10/12/2022 07:30~~",
        PackageIndicator: "",
        State: 1,
        StateSpecified: true,
      },
      {
        NotForGeneralUse: false,
        NotForGeneralUseSpecified: true,
        Segments: [
          {
            ActionStatusCode: "HK",
            ArrivalStation: "LOS",
            CabinOfService: "Y",
            ChangeReasonCode: "",
            DepartureStation: "ABV",
            PriorityCode: "",
            SegmentType: "",
            STA: "2022-10-15T22:55:00",
            STASpecified: true,
            STD: "2022-10-15T21:20:00",
            STDSpecified: true,
            International: false,
            InternationalSpecified: true,
            FlightDesignator: {
              CarrierCode: "Q9",
              FlightNumber: " 303",
              OpSuffix: " ",
            },
            XrefFlightDesignator: null,
            Fares: [
              {
                ClassOfService: "W",
                ClassType: "",
                RuleTariff: "",
                CarrierCode: "Q9",
                RuleNumber: "CLSC",
                FareBasisCode: "WCOW",
                FareSequence: 1,
                FareSequenceSpecified: true,
                FareClassOfService: "W",
                FareStatus: 0,
                FareStatusSpecified: true,
                FareApplicationType: 0,
                FareApplicationTypeSpecified: true,
                OriginalClassOfService: "W",
                XrefClassOfService: "",
                PaxFares: [
                  {
                    PaxType: "ADT",
                    PaxDiscountCode: "",
                    FareDiscountCode: "",
                    ServiceCharges: [
                      {
                        ChargeType: 0,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "",
                        TicketCode: "",
                        CurrencyCode: "NGN",
                        Amount: 46191,
                        AmountSpecified: true,
                        ChargeDetail: "",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 46191,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 2310,
                        AmountSpecified: true,
                        ChargeDetail: "ABV-LOS",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2310,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "YQ",
                        TicketCode: "YQ",
                        CurrencyCode: "NGN",
                        Amount: 3000,
                        AmountSpecified: true,
                        ChargeDetail: "ABV-LOS",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 3000,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 150,
                        AmountSpecified: true,
                        ChargeDetail: "ABV-LOS",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 150,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "QT",
                        TicketCode: "QT",
                        CurrencyCode: "NGN",
                        Amount: 2000,
                        AmountSpecified: true,
                        ChargeDetail: "ABV-LOS",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2000,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                    ],
                    TicketFareBasisCode: "WCOW",
                    ProofOfStatusRequired: false,
                    ProofOfStatusRequiredSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                ProductClass: "GC",
                IsAllotmentMarketFare: false,
                IsAllotmentMarketFareSpecified: true,
                TravelClassCode: "Y",
                FareSellKey: "0~W~~Q9~WCOW~CLSC~~6~1~NABVLOS0060010~X",
                InboundOutbound: 0,
                InboundOutboundSpecified: true,
                FareLink: 6,
                FareLinkSpecified: true,
                FareDesignator: {
                  FareTypeIndicator: "N",
                  CityCode: "ABV",
                  TravelCityCode: "LOS",
                  RuleFareTypeCode: "",
                  BaseFareFareClassCode: "",
                  DowType: "",
                  SeasonType: "",
                  RoutingNumber: 0,
                  RoutingNumberSpecified: true,
                  OneWayRoundTrip: "",
                  OpenJawAllowed: false,
                  OpenJawAllowedSpecified: true,
                  TripDirection: "",
                  FareByRuleAccountCode: "",
                },
                State: 1,
                StateSpecified: true,
              },
            ],
            Legs: [
              {
                ArrivalStation: "LOS",
                DepartureStation: "ABV",
                STA: "2022-10-15T22:55:00",
                STASpecified: true,
                STD: "2022-10-15T21:20:00",
                STDSpecified: true,
                FlightDesignator: {
                  CarrierCode: "Q9",
                  FlightNumber: " 303",
                  OpSuffix: " ",
                },
                LegInfo: {
                  AdjustedCapacity: 70,
                  AdjustedCapacitySpecified: true,
                  EquipmentType: "AT7",
                  EquipmentTypeSuffix: "",
                  ArrivalTerminal: "",
                  ArrvLTV: 60,
                  ArrvLTVSpecified: true,
                  Capacity: 70,
                  CapacitySpecified: true,
                  CodeShareIndicator: " ",
                  DepartureTerminal: "",
                  DeptLTV: 60,
                  DeptLTVSpecified: true,
                  ETicket: false,
                  ETicketSpecified: true,
                  FlifoUpdated: false,
                  FlifoUpdatedSpecified: true,
                  IROP: false,
                  IROPSpecified: true,
                  Status: 0,
                  StatusSpecified: true,
                  Lid: 70,
                  LidSpecified: true,
                  OnTime: " ",
                  PaxSTA: "2022-10-06T11:11:06.1659352",
                  PaxSTASpecified: true,
                  PaxSTD: "2022-10-06T11:11:06.1659352",
                  PaxSTDSpecified: true,
                  PRBCCode: "Y68",
                  ScheduleServiceType: " ",
                  Sold: 1,
                  SoldSpecified: true,
                  OutMoveDays: 365,
                  OutMoveDaysSpecified: true,
                  BackMoveDays: 365,
                  BackMoveDaysSpecified: true,
                  LegNests: [],
                  LegSSRs: [],
                  OperatingFlightNumber: "    ",
                  OperatedByText: "",
                  OperatingCarrier: "",
                  OperatingOpSuffix: " ",
                  SubjectToGovtApproval: false,
                  SubjectToGovtApprovalSpecified: true,
                  MarketingCode: "",
                  ChangeOfDirection: false,
                  ChangeOfDirectionSpecified: true,
                  MarketingOverride: false,
                  MarketingOverrideSpecified: true,
                  AircraftOwner: "",
                  State: 1,
                  StateSpecified: true,
                },
                OperationsInfo: null,
                InventoryLegID: 16810,
                InventoryLegIDSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxBags: [],
            PaxSeats: [
              {
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                ArrivalStation: "LOS",
                DepartureStation: "ABV",
                UnitDesignator: "2C",
                CompartmentDesignator: "Y",
                SeatPreference: 3,
                SeatPreferenceSpecified: true,
                Penalty: 0,
                PenaltySpecified: true,
                SeatTogetherPreference: false,
                SeatTogetherPreferenceSpecified: true,
                PaxSeatInfo: {
                  SeatSet: 4,
                  SeatSetSpecified: true,
                  Deck: 1,
                  DeckSpecified: true,
                  Properties: [
                    {
                      key: "SRVZONE",
                      value: "1",
                    },
                    {
                      key: "AISLE",
                      value: "TRUE",
                    },
                    {
                      key: "INFANT",
                      value: "TRUE",
                    },
                    {
                      key: "TCC",
                      value: "Y",
                    },
                  ],
                },
                SeatStatusCode: "",
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxSSRs: [
              {
                ActionStatusCode: "HK",
                ArrivalStation: "LOS",
                DepartureStation: "ABV",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "I15",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "IBAG15",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: true,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                ArrivalStation: "LOS",
                DepartureStation: "ABV",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "X20",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "XBAG20",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: false,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxSegments: [
              {
                BoardingSequence: "0",
                CreatedDate: "2022-10-06T11:08:55.94Z",
                CreatedDateSpecified: true,
                LiftStatus: 0,
                LiftStatusSpecified: true,
                OverBookIndicator: "",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                PriorityDate: "2022-10-06T11:08:55.97Z",
                PriorityDateSpecified: true,
                TripType: 1,
                TripTypeSpecified: true,
                TimeChanged: false,
                TimeChangedSpecified: true,
                POS: {
                  AgentCode: "WebAnonymous1",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                SourcePOS: {
                  AgentCode: "WebAnonymous1",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                VerifiedTravelDocs: "",
                ModifiedDate: "2022-10-06T11:08:55.94Z",
                ModifiedDateSpecified: true,
                ActivityDate: "2022-10-06T11:08:55.94Z",
                ActivityDateSpecified: true,
                BaggageAllowanceWeight: 0,
                BaggageAllowanceWeightSpecified: true,
                BaggageAllowanceWeightType: 0,
                BaggageAllowanceWeightTypeSpecified: true,
                BaggageAllowanceUsed: false,
                BaggageAllowanceUsedSpecified: true,
                ReferenceNumber: 0,
                ReferenceNumberSpecified: true,
                BoardingPassDetail: null,
                ServiceBundleCode: "CLSC",
                BaggageGroupNumber: 0,
                BaggageGroupNumberSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxTickets: [],
            PaxSeatPreferences: null,
            SalesDate: "2022-10-06T11:08:55.94Z",
            SalesDateSpecified: true,
            SegmentSellKey:
              "Q9~ 303~ ~~ABV~10/15/2022 21:20~LOS~10/15/2022 22:55~~",
            PaxScores: [],
            ChannelType: 4,
            ChannelTypeSpecified: true,
            AvailabilitySourceCode: "",
            InventorySourceCode: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        JourneySellKey:
          "Q9~ 303~ ~~ABV~10/15/2022 21:20~LOS~10/15/2022 22:55~~",
        PackageIndicator: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComments: [],
    BookingQueueInfos: [],
    BookingContacts: [
      {
        TypeCode: "P",
        Names: [
          {
            FirstName: "olabamipe",
            MiddleName: "",
            LastName: "ytee",
            Suffix: "",
            Title: "MR",
            State: 1,
            StateSpecified: true,
          },
        ],
        EmailAddress: "teeola48@gmail.com",
        HomePhone: "9089567856",
        WorkPhone: "9089567856",
        OtherPhone: "9089567856",
        Fax: "",
        CompanyName: "GreenAfrica",
        AddressLine1: "Lagos",
        AddressLine2: "",
        AddressLine3: "",
        City: "Lagos",
        ProvinceState: "LA",
        PostalCode: "",
        CountryCode: "NG",
        CultureCode: "",
        DistributionOption: 2,
        DistributionOptionSpecified: true,
        CustomerNumber: "",
        NotificationPreference: 0,
        NotificationPreferenceSpecified: true,
        SourceOrganization: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    Payments: [
      {
        ReferenceType: 1,
        ReferenceTypeSpecified: true,
        ReferenceID: 39084,
        ReferenceIDSpecified: true,
        PaymentMethodType: 0,
        PaymentMethodTypeSpecified: true,
        PaymentMethodCode: "FL",
        CurrencyCode: "NGN",
        PaymentAmount: 135302,
        PaymentAmountSpecified: true,
        CollectedCurrencyCode: "NGN",
        CollectedAmount: 135302,
        CollectedAmountSpecified: true,
        QuotedCurrencyCode: "NGN",
        QuotedAmount: 135302,
        QuotedAmountSpecified: true,
        Status: 3,
        StatusSpecified: true,
        AccountNumber: "",
        AccountNumberID: 0,
        AccountNumberIDSpecified: true,
        Expiration: "9999-12-31T00:00:00Z",
        ExpirationSpecified: true,
        AuthorizationCode: "",
        AuthorizationStatus: 4,
        AuthorizationStatusSpecified: true,
        ParentPaymentID: 0,
        ParentPaymentIDSpecified: true,
        Transferred: false,
        TransferredSpecified: true,
        ReconcilliationID: 0,
        ReconcilliationIDSpecified: true,
        FundedDate: "1800-01-01T00:00:00Z",
        FundedDateSpecified: true,
        Installments: 0,
        InstallmentsSpecified: true,
        PaymentText: "",
        ChannelType: 4,
        ChannelTypeSpecified: true,
        PaymentNumber: 1,
        PaymentNumberSpecified: true,
        AccountName: "",
        SourcePointOfSale: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        PointOfSale: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        PaymentID: 52593,
        PaymentIDSpecified: true,
        Deposit: false,
        DepositSpecified: true,
        AccountID: 0,
        AccountIDSpecified: true,
        Password: "",
        AccountTransactionCode: "",
        VoucherID: 0,
        VoucherIDSpecified: true,
        VoucherTransactionID: 0,
        VoucherTransactionIDSpecified: true,
        OverrideVoucherRestrictions: false,
        OverrideVoucherRestrictionsSpecified: true,
        OverrideAmount: false,
        OverrideAmountSpecified: true,
        RecordLocator: "",
        PaymentAddedToState: true,
        PaymentAddedToStateSpecified: true,
        DCC: {
          DCCRateID: "00000000-0000-0000-0000-000000000000",
          DCCStatus: 0,
          DCCStatusSpecified: true,
          ValidationDCCApplicable: false,
          ValidationDCCApplicableSpecified: true,
          ValidationDCCRateValue: 0,
          ValidationDCCRateValueSpecified: true,
          ValidationDCCCurrency: "",
          ValidationDCCAmount: 0,
          ValidationDCCAmountSpecified: true,
          ValidationDCCPutInState: "",
        },
        ThreeDSecure: {
          BrowserUserAgent: "",
          BrowserAccept: "",
          RemoteIpAddress: "",
          TermUrl: "",
          ProxyVia: "",
          ValidationTDSApplicable: false,
          ValidationTDSApplicableSpecified: true,
          ValidationTDSPaReq: "",
          ValidationTDSAcsUrl: "",
          ValidationTDSPaRes: "",
          ValidationTDSSuccessful: false,
          ValidationTDSSuccessfulSpecified: true,
          ValidationTDSAuthResult: "",
          ValidationTDSCavv: "",
          ValidationTDSCavvAlgorithm: "",
          ValidationTDSEci: "",
          ValidationTDSXid: "",
        },
        PaymentFields: [
          {
            FieldName: "REF",
            FieldValue: "U4UJ4PZZINQOGCIVK3MLAM7CHG",
          },
        ],
        PaymentAddresses: [],
        CreatedDate: "2022-10-06T11:09:39.22Z",
        CreatedDateSpecified: true,
        CreatedAgentID: 409,
        CreatedAgentIDSpecified: true,
        ModifiedDate: "2022-10-06T11:09:39.22Z",
        ModifiedDateSpecified: true,
        ModifiedAgentID: 409,
        ModifiedAgentIDSpecified: true,
        BinRange: 0,
        BinRangeSpecified: true,
        ApprovalDate: "2022-10-06T11:09:39.237Z",
        ApprovalDateSpecified: true,
        BookingID: 39084,
        BookingIDSpecified: true,
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComponents: [],
    NumericRecordLocator: "062606192631",
    SourceBookingPOS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      ISOCountryCode: "",
      SourceSystemCode: "",
      State: 1,
      StateSpecified: true,
    },
    ReissueCount: 0,
    ReissueCountSpecified: true,
    PricingReissueMode: "16",
    BaggagePricingSystemCode: "1N",
    BaggageAllowanceInfo: null,
    BaggageAllowanceList: [],
    OtherServiceInfoList: [],
  },
};
