export const bookingResponse = {
  Error: null,
  Booking: {
    State: 1,
    StateSpecified: true,
    RecordLocator: "X97F5D",
    CurrencyCode: "NGN",
    PaxCount: 1,
    PaxCountSpecified: true,
    SystemCode: "",
    BookingID: 39175,
    BookingIDSpecified: true,
    BookingParentID: 0,
    BookingParentIDSpecified: true,
    ParentRecordLocator: "",
    BookingChangeCode: "",
    GroupName: "",
    BookingInfo: {
      BookingStatus: 2,
      BookingStatusSpecified: true,
      BookingType: "",
      ChannelType: 2,
      ChannelTypeSpecified: true,
      CreatedDate: "2022-10-17T10:30:02.54Z",
      CreatedDateSpecified: true,
      ExpiredDate: "2022-11-17T04:50:00Z",
      ExpiredDateSpecified: true,
      ModifiedDate: "2022-10-17T10:30:19.26Z",
      ModifiedDateSpecified: true,
      PriceStatus: 2,
      PriceStatusSpecified: true,
      ProfileStatus: 1,
      ProfileStatusSpecified: true,
      ChangeAllowed: true,
      ChangeAllowedSpecified: true,
      CreatedAgentID: 22,
      CreatedAgentIDSpecified: true,
      ModifiedAgentID: 22,
      ModifiedAgentIDSpecified: true,
      BookingDate: "2022-10-17T10:30:02.54Z",
      BookingDateSpecified: true,
      OwningCarrierCode: "Q9",
      PaidStatus: 1,
      PaidStatusSpecified: true,
      ActivityDate: "2022-10-17T10:30:19.26",
      ActivityDateSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    POS: {
      AgentCode: "WebAnonymous",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    SourcePOS: {
      AgentCode: "WebAnonymous",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    TypeOfSale: {
      PaxResidentCountry: "NG",
      PromotionCode: "IBETST01",
      FareTypes: [],
      PromotionSold: true,
      PromotionSoldSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    BookingHold: {
      HoldDateTime: "9999-12-31T00:00:00Z",
      HoldDateTimeSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    BookingSum: {
      BalanceDue: 0.0,
      BalanceDueSpecified: true,
      AuthorizedBalanceDue: 0.0,
      AuthorizedBalanceDueSpecified: true,
      SegmentCount: 1,
      SegmentCountSpecified: true,
      PassiveSegmentCount: 0,
      PassiveSegmentCountSpecified: true,
      TotalCost: 22900.0,
      TotalCostSpecified: true,
      PointsBalanceDue: 0.0,
      PointsBalanceDueSpecified: true,
      TotalPointCost: 0.0,
      TotalPointCostSpecified: true,
      AlternateCurrencyCode: "",
      AlternateCurrencyBalanceDue: 0.0,
      AlternateCurrencyBalanceDueSpecified: true,
    },
    ReceivedBy: {
      ReceivedBy: "",
      ReceivedReference: "",
      ReferralCode: "",
      LatestReceivedBy: "",
      LatestReceivedReference: "",
      State: 1,
      StateSpecified: true,
    },
    RecordLocators: [],
    Passengers: [
      {
        PassengerPrograms: null,
        CustomerNumber: "",
        PassengerNumber: 0,
        PassengerNumberSpecified: true,
        FamilyNumber: 0,
        FamilyNumberSpecified: true,
        PaxDiscountCode: "",
        Names: [
          {
            FirstName: "Kiran",
            MiddleName: "",
            LastName: "Deve",
            Suffix: "",
            Title: "MR",
            State: 1,
            StateSpecified: true,
          },
        ],
        Infant: null,
        PassengerInfo: {
          BalanceDue: 0.0,
          BalanceDueSpecified: true,
          Gender: 0,
          GenderSpecified: true,
          Nationality: "",
          ResidentCountry: "",
          TotalCost: 22900.0,
          TotalCostSpecified: true,
          WeightCategory: 0,
          WeightCategorySpecified: true,
          State: 1,
          StateSpecified: true,
        },
        PassengerProgram: {
          ProgramCode: "",
          ProgramLevelCode: "",
          ProgramNumber: "",
          State: 1,
          StateSpecified: true,
        },
        PassengerFees: [],
        PassengerAddresses: [],
        PassengerTravelDocuments: [],
        PassengerBags: [],
        PassengerID: 52798,
        PassengerIDSpecified: true,
        PassengerTypeInfos: [
          {
            State: 1,
            StateSpecified: true,
            DOB: "2010-01-01T00:00:00",
            DOBSpecified: true,
            PaxType: "ADT",
          },
        ],
        PassengerInfos: [
          {
            BalanceDue: 0.0,
            BalanceDueSpecified: true,
            Gender: 0,
            GenderSpecified: true,
            Nationality: "",
            ResidentCountry: "",
            TotalCost: 22900.0,
            TotalCostSpecified: true,
            WeightCategory: 0,
            WeightCategorySpecified: true,
            State: 1,
            StateSpecified: true,
          },
        ],
        PassengerInfants: [],
        PseudoPassenger: false,
        PseudoPassengerSpecified: true,
        PassengerTypeInfo: {
          State: 1,
          StateSpecified: true,
          DOB: "2010-01-01T00:00:00",
          DOBSpecified: true,
          PaxType: "ADT",
        },
        PassengerEMDCouponList: [],
        State: 1,
        StateSpecified: true,
      },
    ],
    Journeys: [
      {
        NotForGeneralUse: false,
        NotForGeneralUseSpecified: true,
        Segments: [
          {
            ActionStatusCode: "HK",
            ArrivalStation: "ABV",
            CabinOfService: "Y",
            ChangeReasonCode: "",
            DepartureStation: "LOS",
            PriorityCode: "",
            SegmentType: "",
            STA: "2022-11-16T07:30:00",
            STASpecified: true,
            STD: "2022-11-16T05:50:00",
            STDSpecified: true,
            International: false,
            InternationalSpecified: true,
            FlightDesignator: {
              CarrierCode: "Q9",
              FlightNumber: " 300",
              OpSuffix: " ",
            },
            XrefFlightDesignator: null,
            Fares: [
              {
                ClassOfService: "S",
                ClassType: "",
                RuleTariff: "",
                CarrierCode: "Q9",
                RuleNumber: "SAVR",
                FareBasisCode: "SSOW",
                FareSequence: 1,
                FareSequenceSpecified: true,
                FareClassOfService: "S",
                FareStatus: 0,
                FareStatusSpecified: true,
                FareApplicationType: 0,
                FareApplicationTypeSpecified: true,
                OriginalClassOfService: "S",
                XrefClassOfService: "",
                PaxFares: [
                  {
                    PaxType: "ADT",
                    PaxDiscountCode: "",
                    FareDiscountCode: "",
                    ServiceCharges: [
                      {
                        ChargeType: 0,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "",
                        TicketCode: "",
                        CurrencyCode: "NGN",
                        Amount: 33810.0,
                        AmountSpecified: true,
                        ChargeDetail: "",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 33810.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 7,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "IROPC3",
                        TicketCode: "IP3",
                        CurrencyCode: "NGN",
                        Amount: 16905.0,
                        AmountSpecified: true,
                        ChargeDetail: "IROP Compe",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 16905.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 845.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 845.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "YQ",
                        TicketCode: "YQ",
                        CurrencyCode: "NGN",
                        Amount: 3000.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 3000.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 150.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 150.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "QT",
                        TicketCode: "QT",
                        CurrencyCode: "NGN",
                        Amount: 2000.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2000.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                    ],
                    TicketFareBasisCode: "SSOW",
                    ProofOfStatusRequired: false,
                    ProofOfStatusRequiredSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                ProductClass: "GS",
                IsAllotmentMarketFare: false,
                IsAllotmentMarketFareSpecified: true,
                TravelClassCode: "Y",
                FareSellKey: "0~S~~Q9~SSOW~SAVR~~8~1~NABVLOS0080010~X",
                InboundOutbound: 0,
                InboundOutboundSpecified: true,
                FareLink: 8,
                FareLinkSpecified: true,
                FareDesignator: {
                  FareTypeIndicator: "N",
                  CityCode: "ABV",
                  TravelCityCode: "LOS",
                  RuleFareTypeCode: "",
                  BaseFareFareClassCode: "",
                  DowType: "",
                  SeasonType: "",
                  RoutingNumber: 0,
                  RoutingNumberSpecified: true,
                  OneWayRoundTrip: "",
                  OpenJawAllowed: false,
                  OpenJawAllowedSpecified: true,
                  TripDirection: "",
                  FareByRuleAccountCode: "",
                },
                State: 1,
                StateSpecified: true,
              },
            ],
            Legs: [
              {
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                STA: "2022-11-16T07:30:00",
                STASpecified: true,
                STD: "2022-11-16T05:50:00",
                STDSpecified: true,
                FlightDesignator: {
                  CarrierCode: "Q9",
                  FlightNumber: " 300",
                  OpSuffix: " ",
                },
                LegInfo: {
                  AdjustedCapacity: 70,
                  AdjustedCapacitySpecified: true,
                  EquipmentType: "AT7",
                  EquipmentTypeSuffix: "",
                  ArrivalTerminal: "",
                  ArrvLTV: 60,
                  ArrvLTVSpecified: true,
                  Capacity: 70,
                  CapacitySpecified: true,
                  CodeShareIndicator: " ",
                  DepartureTerminal: "",
                  DeptLTV: 60,
                  DeptLTVSpecified: true,
                  ETicket: false,
                  ETicketSpecified: true,
                  FlifoUpdated: false,
                  FlifoUpdatedSpecified: true,
                  IROP: false,
                  IROPSpecified: true,
                  Status: 0,
                  StatusSpecified: true,
                  Lid: 70,
                  LidSpecified: true,
                  OnTime: " ",
                  PaxSTA: "2022-10-17T13:27:48.79854",
                  PaxSTASpecified: true,
                  PaxSTD: "2022-10-17T13:27:48.79854",
                  PaxSTDSpecified: true,
                  PRBCCode: "Y68",
                  ScheduleServiceType: " ",
                  Sold: 1,
                  SoldSpecified: true,
                  OutMoveDays: 365,
                  OutMoveDaysSpecified: true,
                  BackMoveDays: 365,
                  BackMoveDaysSpecified: true,
                  LegNests: [],
                  LegSSRs: [],
                  OperatingFlightNumber: "    ",
                  OperatedByText: "",
                  OperatingCarrier: "",
                  OperatingOpSuffix: " ",
                  SubjectToGovtApproval: false,
                  SubjectToGovtApprovalSpecified: true,
                  MarketingCode: "",
                  ChangeOfDirection: false,
                  ChangeOfDirectionSpecified: true,
                  MarketingOverride: false,
                  MarketingOverrideSpecified: true,
                  AircraftOwner: "",
                  State: 1,
                  StateSpecified: true,
                },
                OperationsInfo: null,
                InventoryLegID: 14625,
                InventoryLegIDSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxBags: [],
            PaxSeats: [],
            PaxSSRs: [],
            PaxSegments: [
              {
                BoardingSequence: "0",
                CreatedDate: "2022-10-17T10:30:02.54Z",
                CreatedDateSpecified: true,
                LiftStatus: 0,
                LiftStatusSpecified: true,
                OverBookIndicator: "",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                PriorityDate: "2022-10-17T10:30:02.747Z",
                PriorityDateSpecified: true,
                TripType: 1,
                TripTypeSpecified: true,
                TimeChanged: false,
                TimeChangedSpecified: true,
                POS: {
                  AgentCode: "WebAnonymous",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                SourcePOS: {
                  AgentCode: "WebAnonymous",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                VerifiedTravelDocs: "",
                ModifiedDate: "2022-10-17T10:30:02.54Z",
                ModifiedDateSpecified: true,
                ActivityDate: "2022-10-17T10:30:02.54Z",
                ActivityDateSpecified: true,
                BaggageAllowanceWeight: 0,
                BaggageAllowanceWeightSpecified: true,
                BaggageAllowanceWeightType: 0,
                BaggageAllowanceWeightTypeSpecified: true,
                BaggageAllowanceUsed: false,
                BaggageAllowanceUsedSpecified: true,
                ReferenceNumber: 0,
                ReferenceNumberSpecified: true,
                BoardingPassDetail: null,
                ServiceBundleCode: "SAVR",
                BaggageGroupNumber: 0,
                BaggageGroupNumberSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxTickets: [],
            PaxSeatPreferences: null,
            SalesDate: "2022-10-17T10:30:02.54Z",
            SalesDateSpecified: true,
            SegmentSellKey:
              "Q9~ 300~ ~~LOS~11/16/2022 05:50~ABV~11/16/2022 07:30~~",
            PaxScores: [],
            ChannelType: 2,
            ChannelTypeSpecified: true,
            AvailabilitySourceCode: "",
            InventorySourceCode: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        JourneySellKey:
          "Q9~ 300~ ~~LOS~11/16/2022 05:50~ABV~11/16/2022 07:30~~",
        PackageIndicator: "0",
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComments: [],
    BookingQueueInfos: [
      {
        PassengerID: 0,
        PassengerIDSpecified: true,
        WatchListID: 1,
        WatchListIDSpecified: true,
        QueueCode: "NOFLY",
        Notes: "Queue Event - Watchlist",
        QueueEventType: 17,
        QueueEventTypeSpecified: true,
        QueueName: "Pax on watch list",
        QueueAction: 5,
        QueueActionSpecified: true,
        QueueMode: 0,
        QueueModeSpecified: true,
        BookingQueueID: 18408,
        BookingQueueIDSpecified: true,
        BookingID: 39175,
        BookingIDSpecified: true,
        SegmentKey: "",
        SubQueueCode: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingContacts: [
      {
        TypeCode: "P",
        Names: [
          {
            FirstName: "Kiran",
            MiddleName: "",
            LastName: "Deve",
            Suffix: "",
            Title: "MR",
            State: 1,
            StateSpecified: true,
          },
        ],
        EmailAddress: "kiran.de@greenafrica.com",
        HomePhone: "234 12345678",
        WorkPhone: "234 12345678",
        OtherPhone: "234 12345678",
        Fax: "",
        CompanyName: "",
        AddressLine1: "Lagos",
        AddressLine2: "",
        AddressLine3: "",
        City: "Lagos",
        ProvinceState: "",
        PostalCode: "",
        CountryCode: "NG",
        CultureCode: "en-US",
        DistributionOption: 0,
        DistributionOptionSpecified: true,
        CustomerNumber: "",
        NotificationPreference: 0,
        NotificationPreferenceSpecified: true,
        SourceOrganization: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    Payments: [
      {
        ReferenceType: 1,
        ReferenceTypeSpecified: true,
        ReferenceID: 39175,
        ReferenceIDSpecified: true,
        PaymentMethodType: 0,
        PaymentMethodTypeSpecified: true,
        PaymentMethodCode: "PS",
        CurrencyCode: "NGN",
        PaymentAmount: 22900.0,
        PaymentAmountSpecified: true,
        CollectedCurrencyCode: "NGN",
        CollectedAmount: 22900.0,
        CollectedAmountSpecified: true,
        QuotedCurrencyCode: "NGN",
        QuotedAmount: 22900.0,
        QuotedAmountSpecified: true,
        Status: 3,
        StatusSpecified: true,
        AccountNumber: "",
        AccountNumberID: 0,
        AccountNumberIDSpecified: true,
        Expiration: "9999-12-31T00:00:00Z",
        ExpirationSpecified: true,
        AuthorizationCode: "",
        AuthorizationStatus: 4,
        AuthorizationStatusSpecified: true,
        ParentPaymentID: 0,
        ParentPaymentIDSpecified: true,
        Transferred: false,
        TransferredSpecified: true,
        ReconcilliationID: 0,
        ReconcilliationIDSpecified: true,
        FundedDate: "1800-01-01T00:00:00Z",
        FundedDateSpecified: true,
        Installments: 0,
        InstallmentsSpecified: true,
        PaymentText: "",
        ChannelType: 2,
        ChannelTypeSpecified: true,
        PaymentNumber: 1,
        PaymentNumberSpecified: true,
        AccountName: "",
        SourcePointOfSale: {
          AgentCode: "WebAnonymous",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        PointOfSale: {
          AgentCode: "WebAnonymous",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        PaymentID: 52696,
        PaymentIDSpecified: true,
        Deposit: false,
        DepositSpecified: true,
        AccountID: 0,
        AccountIDSpecified: true,
        Password: "",
        AccountTransactionCode: "",
        VoucherID: 0,
        VoucherIDSpecified: true,
        VoucherTransactionID: 0,
        VoucherTransactionIDSpecified: true,
        OverrideVoucherRestrictions: false,
        OverrideVoucherRestrictionsSpecified: true,
        OverrideAmount: false,
        OverrideAmountSpecified: true,
        RecordLocator: "",
        PaymentAddedToState: true,
        PaymentAddedToStateSpecified: true,
        DCC: {
          DCCRateID: "00000000-0000-0000-0000-000000000000",
          DCCStatus: 0,
          DCCStatusSpecified: true,
          ValidationDCCApplicable: false,
          ValidationDCCApplicableSpecified: true,
          ValidationDCCRateValue: 0.0,
          ValidationDCCRateValueSpecified: true,
          ValidationDCCCurrency: "",
          ValidationDCCAmount: 0.0,
          ValidationDCCAmountSpecified: true,
          ValidationDCCPutInState: "",
        },
        ThreeDSecure: {
          BrowserUserAgent: "",
          BrowserAccept: "",
          RemoteIpAddress: "",
          TermUrl: "",
          ProxyVia: "",
          ValidationTDSApplicable: false,
          ValidationTDSApplicableSpecified: true,
          ValidationTDSPaReq: "",
          ValidationTDSAcsUrl: "",
          ValidationTDSPaRes: "",
          ValidationTDSSuccessful: false,
          ValidationTDSSuccessfulSpecified: true,
          ValidationTDSAuthResult: "",
          ValidationTDSCavv: "",
          ValidationTDSCavvAlgorithm: "",
          ValidationTDSEci: "",
          ValidationTDSXid: "",
        },
        PaymentFields: [
          { FieldName: "REF", FieldValue: "X97F5DBAO94BH3N7WKZP24XZL9" },
        ],
        PaymentAddresses: [],
        CreatedDate: "2022-10-17T10:30:19.26Z",
        CreatedDateSpecified: true,
        CreatedAgentID: 22,
        CreatedAgentIDSpecified: true,
        ModifiedDate: "2022-10-17T10:30:19.26Z",
        ModifiedDateSpecified: true,
        ModifiedAgentID: 22,
        ModifiedAgentIDSpecified: true,
        BinRange: 0,
        BinRangeSpecified: true,
        ApprovalDate: "2022-10-17T10:30:19.277Z",
        ApprovalDateSpecified: true,
        BookingID: 39175,
        BookingIDSpecified: true,
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComponents: [],
    NumericRecordLocator: "123632112807",
    SourceBookingPOS: {
      AgentCode: "WebAnonymous",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      ISOCountryCode: "",
      SourceSystemCode: "",
      State: 1,
      StateSpecified: true,
    },
    ReissueCount: 0,
    ReissueCountSpecified: true,
    PricingReissueMode: "16",
    BaggagePricingSystemCode: "1N",
    BaggageAllowanceInfo: null,
    BaggageAllowanceList: [],
    OtherServiceInfoList: [],
  },
  LoginIndicator: "1",
  PackageIndicator: "0",
};

export const sessionStateResponse = {
  Error: null,
  BookingData: {
    State: 0,
    StateSpecified: true,
    RecordLocator: "S2N8SY",
    CurrencyCode: "NGN",
    PaxCount: 1,
    PaxCountSpecified: true,
    SystemCode: "",
    BookingID: 39106,
    BookingIDSpecified: true,
    BookingParentID: 0,
    BookingParentIDSpecified: true,
    ParentRecordLocator: "",
    BookingChangeCode: "",
    GroupName: "",
    BookingInfo: {
      BookingStatus: 1,
      BookingStatusSpecified: true,
      BookingType: "",
      ChannelType: 4,
      ChannelTypeSpecified: true,
      CreatedDate: "2022-10-08T12:19:54.147Z",
      CreatedDateSpecified: true,
      ExpiredDate: "2022-10-19T04:50:00Z",
      ExpiredDateSpecified: true,
      ModifiedDate: "2022-10-08T12:19:54.147Z",
      ModifiedDateSpecified: true,
      PriceStatus: 2,
      PriceStatusSpecified: true,
      ProfileStatus: 0,
      ProfileStatusSpecified: true,
      ChangeAllowed: true,
      ChangeAllowedSpecified: true,
      CreatedAgentID: 409,
      CreatedAgentIDSpecified: true,
      ModifiedAgentID: 409,
      ModifiedAgentIDSpecified: true,
      BookingDate: "2022-10-08T12:19:54.147Z",
      BookingDateSpecified: true,
      OwningCarrierCode: "Q9",
      PaidStatus: 0,
      PaidStatusSpecified: true,
      ActivityDate: "2022-10-08T12:19:54.147",
      ActivityDateSpecified: true,
      State: 0,
      StateSpecified: true,
    },
    POS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    SourcePOS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    TypeOfSale: {
      PaxResidentCountry: "NG",
      PromotionCode: "",
      FareTypes: [],
      PromotionSold: false,
      PromotionSoldSpecified: true,
      State: 0,
      StateSpecified: true,
    },
    BookingHold: {
      HoldDateTime: "2022-10-18T04:49:00Z",
      HoldDateTimeSpecified: true,
      State: 0,
      StateSpecified: true,
    },
    BookingSum: {
      BalanceDue: 88651,
      BalanceDueSpecified: true,
      AuthorizedBalanceDue: 88651,
      AuthorizedBalanceDueSpecified: true,
      SegmentCount: 1,
      SegmentCountSpecified: true,
      PassiveSegmentCount: 0,
      PassiveSegmentCountSpecified: true,
      TotalCost: 88651,
      TotalCostSpecified: true,
      PointsBalanceDue: 0,
      PointsBalanceDueSpecified: true,
      TotalPointCost: 0,
      TotalPointCostSpecified: true,
      AlternateCurrencyCode: "",
      AlternateCurrencyBalanceDue: 0,
      AlternateCurrencyBalanceDueSpecified: true,
    },
    ReceivedBy: {
      ReceivedBy: "",
      ReceivedReference: "",
      ReferralCode: "",
      LatestReceivedBy: "",
      LatestReceivedReference: "",
      State: 0,
      StateSpecified: true,
    },
    RecordLocators: [],
    Passengers: [
      {
        PassengerPrograms: null,
        CustomerNumber: "",
        PassengerNumber: 0,
        PassengerNumberSpecified: true,
        FamilyNumber: 0,
        FamilyNumberSpecified: true,
        PaxDiscountCode: "",
        Names: [
          {
            FirstName: "Taiwo",
            MiddleName: "",
            LastName: "Aiyerin",
            Suffix: "",
            Title: "MR",
            State: 0,
            StateSpecified: true,
          },
        ],
        Infant: null,
        PassengerInfo: {
          BalanceDue: 88651,
          BalanceDueSpecified: true,
          Gender: 0,
          GenderSpecified: true,
          Nationality: "",
          ResidentCountry: "",
          TotalCost: 88651,
          TotalCostSpecified: true,
          WeightCategory: 0,
          WeightCategorySpecified: true,
          State: 0,
          StateSpecified: true,
        },
        PassengerProgram: {
          ProgramCode: "",
          ProgramLevelCode: "",
          ProgramNumber: "",
          State: 0,
          StateSpecified: true,
        },
        PassengerFees: [
          {
            ActionStatusCode: "HK",
            FeeCode: "CLSC",
            FeeDetail: "",
            FeeNumber: 0,
            FeeNumberSpecified: true,
            FeeType: 17,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221018 Q9 300 LOSABV",
            Note: "",
            SSRCode: "",
            SSRNumber: 0,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "CLSC",
                TicketCode: "CLS",
                CurrencyCode: "NGN",
                Amount: 0,
                AmountSpecified: true,
                ChargeDetail: "Classic",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 0,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-08T12:19:54.147Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 2,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "XBAG20",
            FeeDetail: "",
            FeeNumber: 1,
            FeeNumberSpecified: true,
            FeeType: 6,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221018 Q9 300 LOSABV",
            Note: "",
            SSRCode: "X20",
            SSRNumber: 1,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "XBAG20",
                TicketCode: "X20",
                CurrencyCode: "NGN",
                Amount: 11429,
                AmountSpecified: true,
                ChargeDetail: "XBAG 20KG",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 11429,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
              {
                ChargeType: 5,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "NG",
                TicketCode: "NG ",
                CurrencyCode: "NGN",
                Amount: 571,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 571,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-08T12:19:54.147Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "XBAG15",
            FeeDetail: "",
            FeeNumber: 2,
            FeeNumberSpecified: true,
            FeeType: 6,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221018 Q9 300 LOSABV",
            Note: "",
            SSRCode: "X15",
            SSRNumber: 1,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "XBAG15",
                TicketCode: "X15",
                CurrencyCode: "NGN",
                Amount: 8571,
                AmountSpecified: true,
                ChargeDetail: "XBAG 15KG",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 8571,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
              {
                ChargeType: 5,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "NG",
                TicketCode: "NG ",
                CurrencyCode: "NGN",
                Amount: 429,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 429,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-08T12:19:54.147Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "XBAG10",
            FeeDetail: "",
            FeeNumber: 3,
            FeeNumberSpecified: true,
            FeeType: 6,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221018 Q9 300 LOSABV",
            Note: "",
            SSRCode: "X10",
            SSRNumber: 1,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "XBAG10",
                TicketCode: "X10",
                CurrencyCode: "NGN",
                Amount: 5714,
                AmountSpecified: true,
                ChargeDetail: "XBAG 10KG",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 5714,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
              {
                ChargeType: 5,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "NG",
                TicketCode: "NG ",
                CurrencyCode: "NGN",
                Amount: 286,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 286,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-08T12:19:54.147Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "XBAG10",
            FeeDetail: "",
            FeeNumber: 4,
            FeeNumberSpecified: true,
            FeeType: 6,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221018 Q9 300 LOSABV",
            Note: "",
            SSRCode: "X10",
            SSRNumber: 2,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "XBAG10",
                TicketCode: "X10",
                CurrencyCode: "NGN",
                Amount: 5714,
                AmountSpecified: true,
                ChargeDetail: "XBAG 10KG",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 5714,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
              {
                ChargeType: 5,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "NG",
                TicketCode: "NG ",
                CurrencyCode: "NGN",
                Amount: 286,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 286,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-08T12:19:54.147Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
          {
            ActionStatusCode: "HK",
            FeeCode: "SEAT",
            FeeDetail: "",
            FeeNumber: 5,
            FeeNumberSpecified: true,
            FeeType: 9,
            FeeTypeSpecified: true,
            FeeOverride: false,
            FeeOverrideSpecified: true,
            FlightReference: "20221018 Q9 300 LOSABV",
            Note: "",
            SSRCode: "",
            SSRNumber: 0,
            SSRNumberSpecified: true,
            PaymentNumber: 0,
            PaymentNumberSpecified: true,
            ServiceCharges: [
              {
                ChargeType: 6,
                ChargeTypeSpecified: true,
                CollectType: 0,
                CollectTypeSpecified: true,
                ChargeCode: "SEAT",
                TicketCode: "STF",
                CurrencyCode: "NGN",
                Amount: 2000,
                AmountSpecified: true,
                ChargeDetail: "LOS-ABV",
                ForeignCurrencyCode: "NGN",
                ForeignAmount: 2000,
                ForeignAmountSpecified: true,
                State: 0,
                StateSpecified: true,
              },
            ],
            CreatedDate: "2022-10-08T12:19:54.147Z",
            CreatedDateSpecified: true,
            IsProtected: false,
            IsProtectedSpecified: true,
            FeeApplicationType: 3,
            FeeApplicationTypeSpecified: true,
            State: 1,
            StateSpecified: true,
          },
        ],
        PassengerAddresses: [],
        PassengerTravelDocuments: [],
        PassengerBags: [],
        PassengerID: 52664,
        PassengerIDSpecified: true,
        PassengerTypeInfos: [
          {
            State: 0,
            StateSpecified: true,
            DOB: "9999-12-31T00:00:00Z",
            DOBSpecified: true,
            PaxType: "ADT",
          },
        ],
        PassengerInfos: [
          {
            BalanceDue: 88651,
            BalanceDueSpecified: true,
            Gender: 0,
            GenderSpecified: true,
            Nationality: "",
            ResidentCountry: "",
            TotalCost: 88651,
            TotalCostSpecified: true,
            WeightCategory: 0,
            WeightCategorySpecified: true,
            State: 0,
            StateSpecified: true,
          },
        ],
        PassengerInfants: [],
        PseudoPassenger: false,
        PseudoPassengerSpecified: true,
        PassengerTypeInfo: {
          State: 0,
          StateSpecified: true,
          DOB: "9999-12-31T00:00:00Z",
          DOBSpecified: true,
          PaxType: "ADT",
        },
        PassengerEMDCouponList: [],
        State: 0,
        StateSpecified: true,
      },
    ],
    Journeys: [
      {
        NotForGeneralUse: false,
        NotForGeneralUseSpecified: true,
        Segments: [
          {
            ActionStatusCode: "HK",
            ArrivalStation: "ABV",
            CabinOfService: "Y",
            ChangeReasonCode: "",
            DepartureStation: "LOS",
            PriorityCode: "",
            SegmentType: "",
            STA: "2022-10-18T07:30:00",
            STASpecified: true,
            STD: "2022-10-18T05:50:00",
            STDSpecified: true,
            International: false,
            InternationalSpecified: true,
            FlightDesignator: {
              CarrierCode: "Q9",
              FlightNumber: " 300",
              OpSuffix: " ",
            },
            XrefFlightDesignator: null,
            Fares: [
              {
                ClassOfService: "W",
                ClassType: "",
                RuleTariff: "",
                CarrierCode: "Q9",
                RuleNumber: "CLSC",
                FareBasisCode: "WCOW",
                FareSequence: 1,
                FareSequenceSpecified: true,
                FareClassOfService: "W",
                FareStatus: 0,
                FareStatusSpecified: true,
                FareApplicationType: 0,
                FareApplicationTypeSpecified: true,
                OriginalClassOfService: "W",
                XrefClassOfService: "",
                PaxFares: [
                  {
                    PaxType: "ADT",
                    PaxDiscountCode: "",
                    FareDiscountCode: "",
                    ServiceCharges: [
                      {
                        ChargeType: 0,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "",
                        TicketCode: "",
                        CurrencyCode: "NGN",
                        Amount: 46191,
                        AmountSpecified: true,
                        ChargeDetail: "",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 46191,
                        ForeignAmountSpecified: true,
                        State: 0,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 2310,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2310,
                        ForeignAmountSpecified: true,
                        State: 0,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "YQ",
                        TicketCode: "YQ",
                        CurrencyCode: "NGN",
                        Amount: 3000,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 3000,
                        ForeignAmountSpecified: true,
                        State: 0,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 150,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 150,
                        ForeignAmountSpecified: true,
                        State: 0,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "QT",
                        TicketCode: "QT",
                        CurrencyCode: "NGN",
                        Amount: 2000,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2000,
                        ForeignAmountSpecified: true,
                        State: 0,
                        StateSpecified: true,
                      },
                    ],
                    TicketFareBasisCode: "WCOW",
                    ProofOfStatusRequired: false,
                    ProofOfStatusRequiredSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                ProductClass: "GC",
                IsAllotmentMarketFare: false,
                IsAllotmentMarketFareSpecified: true,
                TravelClassCode: "Y",
                FareSellKey: "0~W~~Q9~WCOW~CLSC~~6~1~NABVLOS0060010~X",
                InboundOutbound: 0,
                InboundOutboundSpecified: true,
                FareLink: 6,
                FareLinkSpecified: true,
                FareDesignator: {
                  FareTypeIndicator: "N",
                  CityCode: "ABV",
                  TravelCityCode: "LOS",
                  RuleFareTypeCode: "",
                  BaseFareFareClassCode: "",
                  DowType: "",
                  SeasonType: "",
                  RoutingNumber: 0,
                  RoutingNumberSpecified: true,
                  OneWayRoundTrip: "",
                  OpenJawAllowed: false,
                  OpenJawAllowedSpecified: true,
                  TripDirection: "",
                  FareByRuleAccountCode: "",
                },
                State: 0,
                StateSpecified: true,
              },
            ],
            Legs: [
              {
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                STA: "2022-10-18T07:30:00",
                STASpecified: true,
                STD: "2022-10-18T05:50:00",
                STDSpecified: true,
                FlightDesignator: {
                  CarrierCode: "Q9",
                  FlightNumber: " 300",
                  OpSuffix: " ",
                },
                LegInfo: {
                  AdjustedCapacity: 70,
                  AdjustedCapacitySpecified: true,
                  EquipmentType: "AT7",
                  EquipmentTypeSuffix: "",
                  ArrivalTerminal: "",
                  ArrvLTV: 60,
                  ArrvLTVSpecified: true,
                  Capacity: 70,
                  CapacitySpecified: true,
                  CodeShareIndicator: " ",
                  DepartureTerminal: "",
                  DeptLTV: 60,
                  DeptLTVSpecified: true,
                  ETicket: true,
                  ETicketSpecified: true,
                  FlifoUpdated: false,
                  FlifoUpdatedSpecified: true,
                  IROP: false,
                  IROPSpecified: true,
                  Status: 0,
                  StatusSpecified: true,
                  Lid: 70,
                  LidSpecified: true,
                  OnTime: " ",
                  PaxSTA: "2022-10-18T07:30:00",
                  PaxSTASpecified: true,
                  PaxSTD: "2022-10-18T05:50:00",
                  PaxSTDSpecified: true,
                  PRBCCode: "Y68",
                  ScheduleServiceType: "J",
                  Sold: 1,
                  SoldSpecified: true,
                  OutMoveDays: 365,
                  OutMoveDaysSpecified: true,
                  BackMoveDays: 365,
                  BackMoveDaysSpecified: true,
                  LegNests: [
                    {
                      ClassNest: 1,
                      ClassNestSpecified: true,
                      Lid: 70,
                      LidSpecified: true,
                      AdjustedCapacity: 70,
                      AdjustedCapacitySpecified: true,
                      TravelClassCode: "Y",
                      NestType: 1,
                      NestTypeSpecified: true,
                      LegClasses: [
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "K2",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 21,
                          ClassRankSpecified: true,
                          ClassAU: 47,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "H2",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 20,
                          ClassRankSpecified: true,
                          ClassAU: 51,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "M2",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 19,
                          ClassRankSpecified: true,
                          ClassAU: 55,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "Y2",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 18,
                          ClassRankSpecified: true,
                          ClassAU: 66,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "B2",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 17,
                          ClassRankSpecified: true,
                          ClassAU: 59,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "Y",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 16,
                          ClassRankSpecified: true,
                          ClassAU: 68,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "B",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 15,
                          ClassRankSpecified: true,
                          ClassAU: 61,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "M",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 14,
                          ClassRankSpecified: true,
                          ClassAU: 57,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "H",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 13,
                          ClassRankSpecified: true,
                          ClassAU: 53,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "K",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 12,
                          ClassRankSpecified: true,
                          ClassAU: 49,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "L",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 11,
                          ClassRankSpecified: true,
                          ClassAU: 45,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "Q",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 10,
                          ClassRankSpecified: true,
                          ClassAU: 43,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "V",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 9,
                          ClassRankSpecified: true,
                          ClassAU: 41,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "W",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 8,
                          ClassRankSpecified: true,
                          ClassAU: 38,
                          ClassAUSpecified: true,
                          ClassSold: 1,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "U",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 7,
                          ClassRankSpecified: true,
                          ClassAU: 35,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "T",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 6,
                          ClassRankSpecified: true,
                          ClassAU: 32,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "X",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 5,
                          ClassRankSpecified: true,
                          ClassAU: 29,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "N",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 4,
                          ClassRankSpecified: true,
                          ClassAU: 18,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "O",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 3,
                          ClassRankSpecified: true,
                          ClassAU: 15,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "S",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 2,
                          ClassRankSpecified: true,
                          ClassAU: 10,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "R",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 1,
                          ClassRankSpecified: true,
                          ClassAU: 112,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "P",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "X",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 23,
                          ClassRankSpecified: true,
                          ClassAU: 2,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                        {
                          ClassNest: 1,
                          ClassNestSpecified: true,
                          ClassOfService: "I",
                          Status: 0,
                          StatusSpecified: true,
                          ClassType: "X",
                          ClassAllotted: 0,
                          ClassAllottedSpecified: true,
                          ClassRank: 22,
                          ClassRankSpecified: true,
                          ClassAU: 2,
                          ClassAUSpecified: true,
                          ClassSold: 0,
                          ClassSoldSpecified: true,
                          NonStopSold: 0,
                          NonStopSoldSpecified: true,
                          ThruSold: 0,
                          ThruSoldSpecified: true,
                          CnxSold: 0,
                          CnxSoldSpecified: true,
                          LatestAdvRes: 0,
                          LatestAdvResSpecified: true,
                          State: 1,
                          StateSpecified: true,
                        },
                      ],
                      State: 1,
                      StateSpecified: true,
                    },
                  ],
                  LegSSRs: [
                    {
                      SSRNestCode: "BAGS",
                      SSRLid: 100,
                      SSRLidSpecified: true,
                      SSRSold: 0,
                      SSRSoldSpecified: true,
                      SSRValueSold: 0,
                      SSRValueSoldSpecified: true,
                    },
                    {
                      SSRNestCode: "INFT",
                      SSRLid: 6,
                      SSRLidSpecified: true,
                      SSRSold: 0,
                      SSRSoldSpecified: true,
                      SSRValueSold: 0,
                      SSRValueSoldSpecified: true,
                    },
                    {
                      SSRNestCode: "MAAS",
                      SSRLid: 5,
                      SSRLidSpecified: true,
                      SSRSold: 0,
                      SSRSoldSpecified: true,
                      SSRValueSold: 0,
                      SSRValueSoldSpecified: true,
                    },
                  ],
                  OperatingFlightNumber: "    ",
                  OperatedByText: "",
                  OperatingCarrier: "",
                  OperatingOpSuffix: " ",
                  SubjectToGovtApproval: false,
                  SubjectToGovtApprovalSpecified: true,
                  MarketingCode: "",
                  ChangeOfDirection: false,
                  ChangeOfDirectionSpecified: true,
                  MarketingOverride: false,
                  MarketingOverrideSpecified: true,
                  AircraftOwner: "",
                  State: 1,
                  StateSpecified: true,
                },
                OperationsInfo: null,
                InventoryLegID: 14596,
                InventoryLegIDSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxBags: [],
            PaxSeats: [
              {
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                UnitDesignator: "3C",
                CompartmentDesignator: "Y",
                SeatPreference: 3,
                SeatPreferenceSpecified: true,
                Penalty: 0,
                PenaltySpecified: true,
                SeatTogetherPreference: false,
                SeatTogetherPreferenceSpecified: true,
                PaxSeatInfo: {
                  SeatSet: 6,
                  SeatSetSpecified: true,
                  Deck: 1,
                  DeckSpecified: true,
                  Properties: [
                    {
                      key: "SRVZONE",
                      value: "1",
                    },
                    {
                      key: "AISLE",
                      value: "TRUE",
                    },
                    {
                      key: "INFANT",
                      value: "TRUE",
                    },
                    {
                      key: "TCC",
                      value: "Y",
                    },
                  ],
                },
                SeatStatusCode: "",
                State: 0,
                StateSpecified: true,
              },
            ],
            PaxSSRs: [
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "I15",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "IBAG15",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: true,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "X20",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "XBAG20",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: false,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "X15",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "XBAG15",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: false,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "X10",
                SSRNumber: 1,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "XBAG10",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: false,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
              {
                ActionStatusCode: "HK",
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                SSRCode: "X10",
                SSRNumber: 2,
                SSRNumberSpecified: true,
                SSRDetail: "",
                FeeCode: "XBAG10",
                Note: "",
                SSRValue: 1,
                SSRValueSpecified: true,
                IsInServiceBundle: false,
                IsInServiceBundleSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxSegments: [
              {
                BoardingSequence: "",
                CreatedDate: "2022-10-08T12:19:54.147Z",
                CreatedDateSpecified: true,
                LiftStatus: 0,
                LiftStatusSpecified: true,
                OverBookIndicator: "",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                PriorityDate: "2022-10-08T12:19:54.1626584Z",
                PriorityDateSpecified: true,
                TripType: 1,
                TripTypeSpecified: true,
                TimeChanged: false,
                TimeChangedSpecified: true,
                POS: null,
                SourcePOS: null,
                VerifiedTravelDocs: "",
                ModifiedDate: "9999-12-31T00:00:00Z",
                ModifiedDateSpecified: true,
                ActivityDate: "2022-10-08T12:19:54.147Z",
                ActivityDateSpecified: true,
                BaggageAllowanceWeight: 0,
                BaggageAllowanceWeightSpecified: true,
                BaggageAllowanceWeightType: 0,
                BaggageAllowanceWeightTypeSpecified: true,
                BaggageAllowanceUsed: false,
                BaggageAllowanceUsedSpecified: true,
                ReferenceNumber: 0,
                ReferenceNumberSpecified: true,
                BoardingPassDetail: null,
                ServiceBundleCode: "CLSC",
                BaggageGroupNumber: 0,
                BaggageGroupNumberSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxTickets: [],
            PaxSeatPreferences: null,
            SalesDate: "2022-10-08T12:19:54.147Z",
            SalesDateSpecified: true,
            SegmentSellKey:
              "Q9~ 300~ ~~LOS~10/18/2022 05:50~ABV~10/18/2022 07:30~~",
            PaxScores: [],
            ChannelType: 4,
            ChannelTypeSpecified: true,
            AvailabilitySourceCode: "",
            InventorySourceCode: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        JourneySellKey:
          "Q9~ 300~ ~~LOS~10/18/2022 05:50~ABV~10/18/2022 07:30~~",
        PackageIndicator: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComments: [],
    BookingQueueInfos: [],
    BookingContacts: [
      {
        TypeCode: "P",
        Names: [
          {
            FirstName: "Taiwo",
            MiddleName: "",
            LastName: "Aiyerin",
            Suffix: "",
            Title: "MR",
            State: 0,
            StateSpecified: true,
          },
        ],
        EmailAddress: "taiwo.aiyerin@scenariodevelopers.com",
        HomePhone: "9087323423",
        WorkPhone: "9087323423",
        OtherPhone: "9087323423",
        Fax: "",
        CompanyName: "GreenAfrica",
        AddressLine1: "Lagos",
        AddressLine2: "",
        AddressLine3: "",
        City: "Lagos",
        ProvinceState: "LA",
        PostalCode: "",
        CountryCode: "NG",
        CultureCode: "",
        DistributionOption: 2,
        DistributionOptionSpecified: true,
        CustomerNumber: "",
        NotificationPreference: 0,
        NotificationPreferenceSpecified: true,
        SourceOrganization: "",
        State: 0,
        StateSpecified: true,
      },
    ],
    Payments: [],
    BookingComponents: [],
    NumericRecordLocator: "022227340214",
    SourceBookingPOS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      ISOCountryCode: "",
      SourceSystemCode: "",
      State: 1,
      StateSpecified: true,
    },
    ReissueCount: 0,
    ReissueCountSpecified: true,
    PricingReissueMode: "16",
    BaggagePricingSystemCode: "1N",
    BaggageAllowanceInfo: null,
    BaggageAllowanceList: [],
    OtherServiceInfoList: [],
  },
};
