const getBookingWith1X15 = {
  Error: null,
  Booking: {
    State: 1,
    StateSpecified: true,
    RecordLocator: "T9BR2Q",
    CurrencyCode: "NGN",
    PaxCount: 1,
    PaxCountSpecified: true,
    SystemCode: "",
    BookingID: 38489,
    BookingIDSpecified: true,
    BookingParentID: 0,
    BookingParentIDSpecified: true,
    ParentRecordLocator: "",
    BookingChangeCode: "",
    GroupName: "",
    BookingInfo: {
      BookingStatus: 2,
      BookingStatusSpecified: true,
      BookingType: "",
      ChannelType: 4,
      ChannelTypeSpecified: true,
      CreatedDate: "2022-09-03T11:03:44.133Z",
      CreatedDateSpecified: true,
      ExpiredDate: "2022-09-25T10:45:00Z",
      ExpiredDateSpecified: true,
      ModifiedDate: "2022-09-03T11:04:05.357Z",
      ModifiedDateSpecified: true,
      PriceStatus: 2,
      PriceStatusSpecified: true,
      ProfileStatus: 1,
      ProfileStatusSpecified: true,
      ChangeAllowed: true,
      ChangeAllowedSpecified: true,
      CreatedAgentID: 409,
      CreatedAgentIDSpecified: true,
      ModifiedAgentID: 409,
      ModifiedAgentIDSpecified: true,
      BookingDate: "2022-09-03T11:03:44.133Z",
      BookingDateSpecified: true,
      OwningCarrierCode: "Q9",
      PaidStatus: 1,
      PaidStatusSpecified: true,
      ActivityDate: "2022-09-03T11:04:05.357",
      ActivityDateSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    POS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    SourcePOS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      State: 1,
      StateSpecified: true,
    },
    TypeOfSale: {
      PaxResidentCountry: "NG",
      PromotionCode: "",
      FareTypes: [],
      PromotionSold: false,
      PromotionSoldSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    BookingHold: {
      HoldDateTime: "9999-12-31T00:00:00Z",
      HoldDateTimeSpecified: true,
      State: 1,
      StateSpecified: true,
    },
    BookingSum: {
      BalanceDue: 0.0,
      BalanceDueSpecified: true,
      AuthorizedBalanceDue: 0.0,
      AuthorizedBalanceDueSpecified: true,
      SegmentCount: 1,
      SegmentCountSpecified: true,
      PassiveSegmentCount: 0,
      PassiveSegmentCountSpecified: true,
      TotalCost: 33500.0,
      TotalCostSpecified: true,
      PointsBalanceDue: 0.0,
      PointsBalanceDueSpecified: true,
      TotalPointCost: 0.0,
      TotalPointCostSpecified: true,
      AlternateCurrencyCode: "",
      AlternateCurrencyBalanceDue: 0.0,
      AlternateCurrencyBalanceDueSpecified: true,
    },
    ReceivedBy: {
      ReceivedBy: "",
      ReceivedReference: "",
      ReferralCode: "",
      LatestReceivedBy: "",
      LatestReceivedReference: "",
      State: 1,
      StateSpecified: true,
    },
    RecordLocators: [],
    Passengers: [
      {
        PassengerPrograms: null,
        CustomerNumber: "",
        PassengerNumber: 0,
        PassengerNumberSpecified: true,
        FamilyNumber: 0,
        FamilyNumberSpecified: true,
        PaxDiscountCode: "",
        Names: [
          {
            FirstName: "olabamipe",
            MiddleName: "",
            LastName: "tee",
            Suffix: "",
            Title: "MRS",
            State: 1,
            StateSpecified: true,
          },
        ],
        Infant: null,
        PassengerInfo: {
          BalanceDue: 0.0,
          BalanceDueSpecified: true,
          Gender: 0,
          GenderSpecified: true,
          Nationality: "",
          ResidentCountry: "",
          TotalCost: 33500.0,
          TotalCostSpecified: true,
          WeightCategory: 1,
          WeightCategorySpecified: true,
          State: 1,
          StateSpecified: true,
        },
        PassengerProgram: {
          ProgramCode: "",
          ProgramLevelCode: "",
          ProgramNumber: "",
          State: 1,
          StateSpecified: true,
        },
        PassengerFees: [],
        PassengerAddresses: [],
        PassengerTravelDocuments: [],
        PassengerBags: [],
        PassengerID: 51841,
        PassengerIDSpecified: true,
        PassengerTypeInfos: [
          {
            State: 1,
            StateSpecified: true,
            DOB: "9999-12-31T00:00:00Z",
            DOBSpecified: true,
            PaxType: "ADT",
          },
        ],
        PassengerInfos: [
          {
            BalanceDue: 0.0,
            BalanceDueSpecified: true,
            Gender: 0,
            GenderSpecified: true,
            Nationality: "",
            ResidentCountry: "",
            TotalCost: 33500.0,
            TotalCostSpecified: true,
            WeightCategory: 1,
            WeightCategorySpecified: true,
            State: 1,
            StateSpecified: true,
          },
        ],
        PassengerInfants: [],
        PseudoPassenger: false,
        PseudoPassengerSpecified: true,
        PassengerTypeInfo: {
          State: 1,
          StateSpecified: true,
          DOB: "9999-12-31T00:00:00Z",
          DOBSpecified: true,
          PaxType: "ADT",
        },
        PassengerEMDCouponList: [],
        State: 1,
        StateSpecified: true,
      },
    ],
    Journeys: [
      {
        NotForGeneralUse: false,
        NotForGeneralUseSpecified: true,
        Segments: [
          {
            ActionStatusCode: "HK",
            ArrivalStation: "ABV",
            CabinOfService: "Y",
            ChangeReasonCode: "",
            DepartureStation: "LOS",
            PriorityCode: "",
            SegmentType: "",
            STA: "2022-09-24T13:25:00",
            STASpecified: true,
            STD: "2022-09-24T11:45:00",
            STDSpecified: true,
            International: false,
            InternationalSpecified: true,
            FlightDesignator: {
              CarrierCode: "Q9",
              FlightNumber: " 308",
              OpSuffix: " ",
            },
            XrefFlightDesignator: null,
            Fares: [
              {
                ClassOfService: "S",
                ClassType: "",
                RuleTariff: "",
                CarrierCode: "Q9",
                RuleNumber: "SAVR",
                FareBasisCode: "SSOW",
                FareSequence: 1,
                FareSequenceSpecified: true,
                FareClassOfService: "S",
                FareStatus: 0,
                FareStatusSpecified: true,
                FareApplicationType: 0,
                FareApplicationTypeSpecified: true,
                OriginalClassOfService: "S",
                XrefClassOfService: "",
                PaxFares: [
                  {
                    PaxType: "ADT",
                    PaxDiscountCode: "",
                    FareDiscountCode: "",
                    ServiceCharges: [
                      {
                        ChargeType: 0,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "",
                        TicketCode: "",
                        CurrencyCode: "NGN",
                        Amount: 27000.0,
                        AmountSpecified: true,
                        ChargeDetail: "",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 27000.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 1350.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 1350.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "YQ",
                        TicketCode: "YQ",
                        CurrencyCode: "NGN",
                        Amount: 3000.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 3000.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 5,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "NG",
                        TicketCode: "NG ",
                        CurrencyCode: "NGN",
                        Amount: 150.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 150.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                      {
                        ChargeType: 4,
                        ChargeTypeSpecified: true,
                        CollectType: 0,
                        CollectTypeSpecified: true,
                        ChargeCode: "QT",
                        TicketCode: "QT",
                        CurrencyCode: "NGN",
                        Amount: 2000.0,
                        AmountSpecified: true,
                        ChargeDetail: "LOS-ABV",
                        ForeignCurrencyCode: "NGN",
                        ForeignAmount: 2000.0,
                        ForeignAmountSpecified: true,
                        State: 1,
                        StateSpecified: true,
                      },
                    ],
                    TicketFareBasisCode: "SSOW",
                    ProofOfStatusRequired: false,
                    ProofOfStatusRequiredSpecified: true,
                    State: 1,
                    StateSpecified: true,
                  },
                ],
                ProductClass: "GS",
                IsAllotmentMarketFare: false,
                IsAllotmentMarketFareSpecified: true,
                TravelClassCode: "Y",
                FareSellKey: "0~S~~Q9~SSOW~SAVR~~6~1~NABVLOS0060010~X",
                InboundOutbound: 0,
                InboundOutboundSpecified: true,
                FareLink: 6,
                FareLinkSpecified: true,
                FareDesignator: {
                  FareTypeIndicator: "N",
                  CityCode: "ABV",
                  TravelCityCode: "LOS",
                  RuleFareTypeCode: "",
                  BaseFareFareClassCode: "",
                  DowType: "",
                  SeasonType: "",
                  RoutingNumber: 0,
                  RoutingNumberSpecified: true,
                  OneWayRoundTrip: "",
                  OpenJawAllowed: false,
                  OpenJawAllowedSpecified: true,
                  TripDirection: "",
                  FareByRuleAccountCode: "",
                },
                State: 1,
                StateSpecified: true,
              },
            ],
            Legs: [
              {
                ArrivalStation: "ABV",
                DepartureStation: "LOS",
                STA: "2022-09-24T13:25:00",
                STASpecified: true,
                STD: "2022-09-24T11:45:00",
                STDSpecified: true,
                FlightDesignator: {
                  CarrierCode: "Q9",
                  FlightNumber: " 308",
                  OpSuffix: " ",
                },
                LegInfo: {
                  AdjustedCapacity: 70,
                  AdjustedCapacitySpecified: true,
                  EquipmentType: "AT7",
                  EquipmentTypeSuffix: "",
                  ArrivalTerminal: "",
                  ArrvLTV: 60,
                  ArrvLTVSpecified: true,
                  Capacity: 70,
                  CapacitySpecified: true,
                  CodeShareIndicator: " ",
                  DepartureTerminal: "",
                  DeptLTV: 60,
                  DeptLTVSpecified: true,
                  ETicket: false,
                  ETicketSpecified: true,
                  FlifoUpdated: false,
                  FlifoUpdatedSpecified: true,
                  IROP: false,
                  IROPSpecified: true,
                  Status: 0,
                  StatusSpecified: true,
                  Lid: 70,
                  LidSpecified: true,
                  OnTime: " ",
                  PaxSTA: "2022-09-03T11:11:08.1249296",
                  PaxSTASpecified: true,
                  PaxSTD: "2022-09-03T11:11:08.1249296",
                  PaxSTDSpecified: true,
                  PRBCCode: "Y68",
                  ScheduleServiceType: " ",
                  Sold: 1,
                  SoldSpecified: true,
                  OutMoveDays: 365,
                  OutMoveDaysSpecified: true,
                  BackMoveDays: 365,
                  BackMoveDaysSpecified: true,
                  LegNests: [],
                  LegSSRs: [],
                  OperatingFlightNumber: "    ",
                  OperatedByText: "",
                  OperatingCarrier: "",
                  OperatingOpSuffix: " ",
                  SubjectToGovtApproval: false,
                  SubjectToGovtApprovalSpecified: true,
                  MarketingCode: "",
                  ChangeOfDirection: false,
                  ChangeOfDirectionSpecified: true,
                  MarketingOverride: false,
                  MarketingOverrideSpecified: true,
                  AircraftOwner: "",
                  State: 1,
                  StateSpecified: true,
                },
                OperationsInfo: null,
                InventoryLegID: 16409,
                InventoryLegIDSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxBags: [],
            PaxSeats: [],
            PaxSSRs: [],
            PaxSegments: [
              {
                BoardingSequence: "0",
                CreatedDate: "2022-09-03T11:03:44.133Z",
                CreatedDateSpecified: true,
                LiftStatus: 0,
                LiftStatusSpecified: true,
                OverBookIndicator: "",
                PassengerNumber: 0,
                PassengerNumberSpecified: true,
                PriorityDate: "2022-09-03T11:03:44.143Z",
                PriorityDateSpecified: true,
                TripType: 1,
                TripTypeSpecified: true,
                TimeChanged: false,
                TimeChangedSpecified: true,
                POS: {
                  AgentCode: "WebAnonymous1",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                SourcePOS: {
                  AgentCode: "WebAnonymous1",
                  OrganizationCode: "Q9",
                  DomainCode: "WW2",
                  LocationCode: "WWW",
                  State: 1,
                  StateSpecified: true,
                },
                VerifiedTravelDocs: "",
                ModifiedDate: "2022-09-03T11:03:44.133Z",
                ModifiedDateSpecified: true,
                ActivityDate: "2022-09-03T11:03:44.133Z",
                ActivityDateSpecified: true,
                BaggageAllowanceWeight: 0,
                BaggageAllowanceWeightSpecified: true,
                BaggageAllowanceWeightType: 0,
                BaggageAllowanceWeightTypeSpecified: true,
                BaggageAllowanceUsed: false,
                BaggageAllowanceUsedSpecified: true,
                ReferenceNumber: 0,
                ReferenceNumberSpecified: true,
                BoardingPassDetail: null,
                ServiceBundleCode: "",
                BaggageGroupNumber: 0,
                BaggageGroupNumberSpecified: true,
                State: 1,
                StateSpecified: true,
              },
            ],
            PaxTickets: [],
            PaxSeatPreferences: null,
            SalesDate: "2022-09-03T11:03:44.133Z",
            SalesDateSpecified: true,
            SegmentSellKey:
              "Q9~ 308~ ~~LOS~09/24/2022 11:45~ABV~09/24/2022 13:25~~",
            PaxScores: [],
            ChannelType: 4,
            ChannelTypeSpecified: true,
            AvailabilitySourceCode: "",
            InventorySourceCode: "",
            State: 1,
            StateSpecified: true,
          },
        ],
        JourneySellKey:
          "Q9~ 308~ ~~LOS~09/24/2022 11:45~ABV~09/24/2022 13:25~~",
        PackageIndicator: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComments: [],
    BookingQueueInfos: [],
    BookingContacts: [
      {
        TypeCode: "P",
        Names: [
          {
            FirstName: "olabamipe",
            MiddleName: "",
            LastName: "tee",
            Suffix: "",
            Title: "MRS",
            State: 1,
            StateSpecified: true,
          },
        ],
        EmailAddress: "teeola48@gmail.com",
        HomePhone: "9034567890",
        WorkPhone: "9034567890",
        OtherPhone: "9034567890",
        Fax: "",
        CompanyName: "GreenAfrica",
        AddressLine1: "Lagos",
        AddressLine2: "",
        AddressLine3: "",
        City: "Lagos",
        ProvinceState: "LA",
        PostalCode: "",
        CountryCode: "NG",
        CultureCode: "",
        DistributionOption: 2,
        DistributionOptionSpecified: true,
        CustomerNumber: "",
        NotificationPreference: 0,
        NotificationPreferenceSpecified: true,
        SourceOrganization: "",
        State: 1,
        StateSpecified: true,
      },
    ],
    Payments: [
      {
        ReferenceType: 1,
        ReferenceTypeSpecified: true,
        ReferenceID: 38489,
        ReferenceIDSpecified: true,
        PaymentMethodType: 0,
        PaymentMethodTypeSpecified: true,
        PaymentMethodCode: "PS",
        CurrencyCode: "NGN",
        PaymentAmount: 33500.0,
        PaymentAmountSpecified: true,
        CollectedCurrencyCode: "NGN",
        CollectedAmount: 33500.0,
        CollectedAmountSpecified: true,
        QuotedCurrencyCode: "NGN",
        QuotedAmount: 33500.0,
        QuotedAmountSpecified: true,
        Status: 3,
        StatusSpecified: true,
        AccountNumber: "",
        AccountNumberID: 0,
        AccountNumberIDSpecified: true,
        Expiration: "9999-12-31T00:00:00Z",
        ExpirationSpecified: true,
        AuthorizationCode: "",
        AuthorizationStatus: 4,
        AuthorizationStatusSpecified: true,
        ParentPaymentID: 0,
        ParentPaymentIDSpecified: true,
        Transferred: false,
        TransferredSpecified: true,
        ReconcilliationID: 0,
        ReconcilliationIDSpecified: true,
        FundedDate: "1800-01-01T00:00:00Z",
        FundedDateSpecified: true,
        Installments: 0,
        InstallmentsSpecified: true,
        PaymentText: "",
        ChannelType: 4,
        ChannelTypeSpecified: true,
        PaymentNumber: 1,
        PaymentNumberSpecified: true,
        AccountName: "",
        SourcePointOfSale: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        PointOfSale: {
          AgentCode: "WebAnonymous1",
          OrganizationCode: "Q9",
          DomainCode: "WW2",
          LocationCode: "WWW",
          State: 1,
          StateSpecified: true,
        },
        PaymentID: 51771,
        PaymentIDSpecified: true,
        Deposit: false,
        DepositSpecified: true,
        AccountID: 0,
        AccountIDSpecified: true,
        Password: "",
        AccountTransactionCode: "",
        VoucherID: 0,
        VoucherIDSpecified: true,
        VoucherTransactionID: 0,
        VoucherTransactionIDSpecified: true,
        OverrideVoucherRestrictions: false,
        OverrideVoucherRestrictionsSpecified: true,
        OverrideAmount: false,
        OverrideAmountSpecified: true,
        RecordLocator: "",
        PaymentAddedToState: true,
        PaymentAddedToStateSpecified: true,
        DCC: {
          DCCRateID: "00000000-0000-0000-0000-000000000000",
          DCCStatus: 0,
          DCCStatusSpecified: true,
          ValidationDCCApplicable: false,
          ValidationDCCApplicableSpecified: true,
          ValidationDCCRateValue: 0.0,
          ValidationDCCRateValueSpecified: true,
          ValidationDCCCurrency: "",
          ValidationDCCAmount: 0.0,
          ValidationDCCAmountSpecified: true,
          ValidationDCCPutInState: "",
        },
        ThreeDSecure: {
          BrowserUserAgent: "",
          BrowserAccept: "",
          RemoteIpAddress: "",
          TermUrl: "",
          ProxyVia: "",
          ValidationTDSApplicable: false,
          ValidationTDSApplicableSpecified: true,
          ValidationTDSPaReq: "",
          ValidationTDSAcsUrl: "",
          ValidationTDSPaRes: "",
          ValidationTDSSuccessful: false,
          ValidationTDSSuccessfulSpecified: true,
          ValidationTDSAuthResult: "",
          ValidationTDSCavv: "",
          ValidationTDSCavvAlgorithm: "",
          ValidationTDSEci: "",
          ValidationTDSXid: "",
        },
        PaymentFields: [
          { FieldName: "REF", FieldValue: "T9BR2Q60KO8VGMSNBCMPVULVVP" },
        ],
        PaymentAddresses: [],
        CreatedDate: "2022-09-03T11:04:05.357Z",
        CreatedDateSpecified: true,
        CreatedAgentID: 409,
        CreatedAgentIDSpecified: true,
        ModifiedDate: "2022-09-03T11:04:05.357Z",
        ModifiedDateSpecified: true,
        ModifiedAgentID: 409,
        ModifiedAgentIDSpecified: true,
        BinRange: 0,
        BinRangeSpecified: true,
        ApprovalDate: "2022-09-03T11:04:05.39Z",
        ApprovalDateSpecified: true,
        BookingID: 38489,
        BookingIDSpecified: true,
        State: 1,
        StateSpecified: true,
      },
    ],
    BookingComponents: [],
    NumericRecordLocator: "043603352233",
    SourceBookingPOS: {
      AgentCode: "WebAnonymous1",
      OrganizationCode: "Q9",
      DomainCode: "WW2",
      LocationCode: "WWW",
      ISOCountryCode: "",
      SourceSystemCode: "",
      State: 1,
      StateSpecified: true,
    },
    ReissueCount: 0,
    ReissueCountSpecified: true,
    PricingReissueMode: "16",
    BaggagePricingSystemCode: "1N",
    BaggageAllowanceInfo: null,
    BaggageAllowanceList: [],
    OtherServiceInfoList: [],
  },
};
