const SSRAvailabilityResponse = {
  Error: null,
  SSRAvailabilityForBookingResponse: {
    SSRSegmentList: [
      {
        LegKey: {
          DepartureDate: "2022-08-28T00:00:00",
          DepartureDateSpecified: true,
          DepartureStation: "ABV",
          ArrivalStation: "LOS",
          CarrierCode: "Q9",
          FlightNumber: " 301",
          OpSuffix: " ",
        },
        AvailablePaxSSRList: [
          {
            SSRCode: "X20",
            InventoryControlled: true,
            InventoryControlledSpecified: true,
            NonInventoryControlled: false,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 87,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "XBAG20",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "XBAG20",
                      TicketCode: "X20",
                      CurrencyCode: "NGN",
                      Amount: 5000,
                      AmountSpecified: true,
                      ChargeDetail: "XBAG 20KG",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 5000,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    {
                      ChargeType: 5,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "NG",
                      TicketCode: "NG ",
                      CurrencyCode: "NGN",
                      Amount: 250,
                      AmountSpecified: true,
                      ChargeDetail: "ABV-LOS",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 250,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
          {
            SSRCode: "X15",
            InventoryControlled: true,
            InventoryControlledSpecified: true,
            NonInventoryControlled: false,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 87,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "XBAG15",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "XBAG15",
                      TicketCode: "X15",
                      CurrencyCode: "NGN",
                      Amount: 4500,
                      AmountSpecified: true,
                      ChargeDetail: "XBAG 15KG",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 4500,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                    {
                      ChargeType: 5,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "NG",
                      TicketCode: "NG ",
                      CurrencyCode: "NGN",
                      Amount: 225,
                      AmountSpecified: true,
                      ChargeDetail: "ABV-LOS",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 225,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
          {
            SSRCode: "X10",
            InventoryControlled: true,
            InventoryControlledSpecified: true,
            NonInventoryControlled: false,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 87,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "XBAG10",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "XBAG10",
                      TicketCode: "X10",
                      CurrencyCode: "NGN",
                      Amount: 0,
                      AmountSpecified: true,
                      ChargeDetail: "for free",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 0,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
          {
            SSRCode: "PCK",
            InventoryControlled: false,
            InventoryControlledSpecified: true,
            NonInventoryControlled: true,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 0,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "PCK",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "PCK",
                      TicketCode: "PCK",
                      CurrencyCode: "NGN",
                      Amount: 3000,
                      AmountSpecified: true,
                      ChargeDetail: "Priority C",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 3000,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
          {
            SSRCode: "MAAS",
            InventoryControlled: true,
            InventoryControlledSpecified: true,
            NonInventoryControlled: false,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 5,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [],
            SSRLegList: [],
          },
          {
            SSRCode: "INFT",
            InventoryControlled: true,
            InventoryControlledSpecified: true,
            NonInventoryControlled: false,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 6,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "INFT",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "INFT",
                      TicketCode: "INF",
                      CurrencyCode: "NGN",
                      Amount: 10000,
                      AmountSpecified: true,
                      ChargeDetail: "Infant in ",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 10000,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
          {
            SSRCode: "I23",
            InventoryControlled: false,
            InventoryControlledSpecified: true,
            NonInventoryControlled: true,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 0,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "IBAG23",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "IBAG23",
                      TicketCode: "I23",
                      CurrencyCode: "NGN",
                      Amount: 0,
                      AmountSpecified: true,
                      ChargeDetail: "Inclusive ",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 0,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
          {
            SSRCode: "I15",
            InventoryControlled: false,
            InventoryControlledSpecified: true,
            NonInventoryControlled: true,
            NonInventoryControlledSpecified: true,
            SeatDependent: false,
            SeatDependentSpecified: true,
            NonSeatDependent: true,
            NonSeatDependentSpecified: true,
            Available: 0,
            AvailableSpecified: true,
            PassengerNumberList: [0],
            PaxSSRPriceList: [
              {
                PaxFee: {
                  ActionStatusCode: "NN",
                  FeeCode: "IBAG15",
                  FeeDetail: "",
                  FeeNumber: 0,
                  FeeNumberSpecified: true,
                  FeeType: 6,
                  FeeTypeSpecified: true,
                  FeeOverride: false,
                  FeeOverrideSpecified: true,
                  FlightReference: "",
                  Note: "",
                  SSRCode: "",
                  SSRNumber: 0,
                  SSRNumberSpecified: true,
                  PaymentNumber: 0,
                  PaymentNumberSpecified: true,
                  ServiceCharges: [
                    {
                      ChargeType: 6,
                      ChargeTypeSpecified: true,
                      CollectType: 0,
                      CollectTypeSpecified: true,
                      ChargeCode: "IBAG15",
                      TicketCode: "I15",
                      CurrencyCode: "NGN",
                      Amount: 0,
                      AmountSpecified: true,
                      ChargeDetail: "for free",
                      ForeignCurrencyCode: "NGN",
                      ForeignAmount: 0,
                      ForeignAmountSpecified: true,
                      State: 0,
                      StateSpecified: true,
                    },
                  ],
                  CreatedDate: "2022-08-25T11:31:55.6247091Z",
                  CreatedDateSpecified: true,
                  IsProtected: false,
                  IsProtectedSpecified: true,
                  FeeApplicationType: 3,
                  FeeApplicationTypeSpecified: true,
                  State: 0,
                  StateSpecified: true,
                },
                PassengerNumberList: [0],
              },
            ],
            SSRLegList: [],
          },
        ],
      },
    ],
    OtherServiceInfoList: [],
  },
};
